@echo off
echo Starting Smart Xerox App...

echo Starting Server...
start "Smart Xerox Server" cmd /k "cd server && npm run dev"

echo Starting Client...
start "Smart Xerox Client" cmd /k "cd client && npm run dev"

echo Done! Application is starting...
