export const resources = {
    en: {
        translation: {
            "welcome": "Welcome",
            "login_title": "Welcome Back",
            "signup_title": "Create Account",
            "subtitle_login": "Sign in to continue printing",
            "subtitle_signup": "Join us for smart printing",
            "mobile": "Mobile Number",
            "name": "Full Name",
            "otp": "Enter OTP",
            "send_otp": "Send OTP",
            "verify_otp": "Verify & Login",
            "verify_signup": "Verify & Sign Up",
            "google_login": "Continue with Google",
            "home": "Home",
            "dashboard": "Dashboard",
            "logout": "Logout",
            "login": "Login",
            "signup": "Sign Up",
            "brand_name": "Smart Xerox",
            "nav_dashboard": "Dashboard",
            "nav_login": "Login",
            "nav_signup": "Sign Up",
            "nav_logout": "Logout",
            "nav_profile": "Profile",
            "create_account": "Create Account",
            "welcome_back": "Welcome Back",
            "signup_subtitle": "Join the smartest printing network",
            "login_subtitle": "Continue your premium experience",
            "confirm_pass": "Confirm Password",
            "login_btn": "Sign In",
            "already_account": "Already have an account?",
            "no_account": "Don't have an account?",
            "demo_otp": "Use 1234 for demo",
            "overview": "Overview",
            "services": "Services",
            "support": "Support",
            "profile": "Profile",
            "total_orders": "Total Orders",
            "total_spent": "Total Spent",
            "saved": "Saved",
            "trusted_users": "Trusted Users",
            "recent_orders": "Recent Orders",
            "our_services": "Our Services & Pricing",
            "service_type": "Service Type",
            "single_side": "Single Side",
            "double_side": "Double Side",
            "bulk_print": "Bulk (>100 Pages)",
            "bw_print": "Black & White Print",
            "bw_xerox": "Xerox (B&W)",
            "color_print": "Color Print (Standard)",
            "color_glossy": "Color Print (Glossy)",
            "spiral": "Spiral Binding",
            "glass_binding": "Glass Sheet Binding",
            "account_settings": "Account Settings",
            "update_pass_desc": "Update your password or manage your account details.",
            "go_profile": "Go to Full Profile Settings",
            "no_orders": "No orders found. Start your first print!",
            "newOrder": "New Order",
            "amount": "Amount",
            "pages": "Pages",
            "downloadInvoice": "Download Invoice",
            "personal_info": "Personal Information",
            "email_addr": "Email Address",
            "mobile_num": "Mobile Number",
            "order_history": "Order History",
            "change_pass": "Change Password",
            "current_pass": "Current Password",
            "new_pass": "New Password",
            "update_pass_btn": "Update Password",
            "security": "Security",
            "my_details": "My Details",
            "my_orders": "My Orders",
            "new_print_order": "New Print Order",
            "click_upload": "Click to upload Document",
            "pages_count": "Pages detected",
            "print_type": "Print Type",
            "bw_option": "Black & White",
            "color_option": "Color",
            "copies": "Copies",
            "total_estimate": "Total Estimate",
            "proceed_payment": "Proceed to Payment",
            "payment_success": "Payment Successful!",
            "order_processing": "Your order is being processed.",
            "complete_payment": "Complete Payment",
            "scan_pay": "Scan & Pay 50% advance to confirm",
            "order_total": "Order Total",
            "pay_now": "Pay Now (50%)",
            "i_have_paid": "I Have Paid",
            "cancel_order": "Cancel Order",
            "plus_3_week": "+3 this week",
            "secure_100": "100% Secure",
            "students_count": "1,200+ Students",
            "create_first_order": "Create First Order",
            "history_appear_here": "Your printing history will appear here. Start your first print in seconds!",
            "view_services": "View Services",
            "launching_soon": "Coming Soon",
            "rated_1": "Rated #1 Student Choice",
            "printing_reimagined": "Printing Reimagined.",
            "instant_smart": "Instant & Smart.",
            "hero_desc": "Upload documents from anywhere, pay securely, and pick up in seconds. The future of campus printing is here.",
            "get_started": "Get Started Now",
            "view_pricing": "View Pricing",
            "printing_analytics": "Printing Analytics",
            "total_savings": "Total Savings",
            "plus_12_month": "+12% this month",
            "active_orders": "Active Orders",
            "pending": "Pending",
            "unbeatable_pricing": "Unbeatable Pricing",
            "pricing_sub": "Transparent costs. No hidden fees. Student friendly.",
            "front_page": "Front Page",
            "front_back": "Front & Back",
            "lightning_fast": "Lightning Fast",
            "fast_desc": "Order online and collect before you even reach the shop.",
            "secure_payments": "Secure Payments",
            "secure_desc": "100% secure QR code and UPI payments integration.",
            "anywhere_access": "Anywhere Access",
            "access_desc": "Upload files from your phone, laptop, or tablet instantly.",
            "add_items": "Add Items to Print",
            "your_list": "Your Order List",
            "multi_items": "Multiple Items",
            "pdf_module": "PDF Module",
            "doc_module": "Document Module",
            "upload_pdf_title": "Upload PDF",
            "browse_files": "Click to browse your files",
            "preview": "Preview",
            "edit_pages": "Edit Pages",
            "manual_format": "Manual Formatting",
            "manual_format_desc": "Word documents require manual processing to ensure perfect layout. Please verify via WhatsApp.",
            "chat_whatsapp": "Chat on WhatsApp",
            "special_instr": "Special Instructions",
            "instr_placeholder": "E.g. Spiral Binding, Lamination, Print only odd pages...",
            "advance_pay_label": "Advance to Pay (50%)",
            "submit_pay": "Submit & Pay",
            "premium_services": "Premium Services",
            "word_docs": "Word Documents",
            "word_coming_soon": "Upload, Edit & Converter features are",
            "live_pdf_editor": "Live PDF Editor",
            "live_editor_desc": "No need for external tools. Remove unwanted pages, rotate orientation, and finalize your doc right here in our tab.",
            "digital_deliver": "Digital Delivery",
            "digital_desc": "Get digital copies alongside your physical prints. We store your important docs securely for easy re-ordering.",
            "quality_quote": "\"Where Quality Meets Speed\"",
            "new_feature": "New Feature",
            "contact_support": "Contact & Support",
            "need_help_desc": "Need help with an order? Want manual document formatting? Chat with us directly on WhatsApp.",
            "support_hours": "Support Hours",
            "trust_secure": "100% Secure",
            "trust_secure_desc": "Encrypted payments & data privacy",
            "trust_fast": "Lightning Fast",
            "trust_fast_desc": "24h delivery guarantee",
            "trust_quality": "Best Quality",
            "trust_quality_desc": "Premium paper & crisp prints",
            "spending_analysis": "Spending Analysis",
            "last_7_days": "Last 7 Days",
            "daily_quote": "Daily Motivation",
            "design_quote": "Design is not just what it looks like and feels like. Design is how it works.",
            "lic_footer": "Licensed by Smart Xerox & Co. \u00A9 2024",
            "made_with_love": "Made with \u2764\uFE0F for Students",
            "morning_express": "Morning Express",
            "morning_desc": "Order before 8 AM, Pickup by 10:30 AM.",
            "live_pdf_desc": "Edit, Rotate, Delete pages instantly.",
            "glass_binding": "Glass Sheet Binding",
            "glass_desc": "Premium binding for valid documents.",
            "conditions_apply": "Conditions Apply",
            "track_latest": "Live Status: Latest Order",
            "quote_1": "Technology is best when it brings people together.",
            "quote_author_1": "Matt Mullenweg",
            "quote_2": "It's not a bug, it's a feature.",
            "quote_author_2": "Unknown",
            "quote_3": "Talk is cheap. Show me the code.",
            "quote_author_3": "Linus Torvalds",
            "quote_4": "Simplicity is the soul of efficiency.",
            "quote_author_4": "Austin Freeman",
            "quote_5": "Stay hungry, stay foolish.",
            "quote_author_5": "Steve Jobs"
        }
    },
    hi: {
        translation: {
            "welcome": "स्वागत है",
            "login_title": "वापसी पर स्वागत है",
            "signup_title": "खाता बनाएं",
            "subtitle_login": "प्रिंटिंग जारी रखने के लिए साइन इन करें",
            "subtitle_signup": "स्मार्ट प्रिंटिंग के लिए हमसे जुड़ें",
            "mobile": "मोबाइल नंबर",
            "name": "पूरा नाम",
            "otp": "ओटीपी दर्ज करें",
            "send_otp": "ओटीपी भेजें",
            "verify_otp": "सत्यापित करें और लॉगिन करें",
            "verify_signup": "सत्यापित करें और साइन अप करें",
            "google_login": "Google के साथ जारी रखें",
            "home": "होम",
            "dashboard": "डैशबोर्ड",
            "logout": "लॉग आउट",
            "login": "लॉगिन",
            "signup": "साइन अप",
            "brand_name": "स्मार्ट ज़ेरॉक्स",
            "nav_dashboard": "डैशबोर्ड",
            "nav_login": "लॉगिन",
            "nav_signup": "साइन अप",
            "nav_logout": "लॉग आउट",
            "nav_profile": "प्रोफ़ाइल",
            "create_account": "खाता बनाएं",
            "welcome_back": "वापसी पर स्वागत है",
            "signup_subtitle": "स्मार्ट प्रिंटिंग नेटवर्क से जुड़ें",
            "login_subtitle": "अपना अनुभव जारी रखें",
            "confirm_pass": "पासवर्ड की पुष्टि करें",
            "login_btn": "साइन इन करें",
            "already_account": "क्या आपके पास पहले से एक खाता है?",
            "no_account": "क्या कोई खाता नहीं है?",
            "demo_otp": "डेमो के लिए 1234 का उपयोग करें",
            "overview": "अवलोकन",
            "services": "सेवाएं",
            "support": "सहायता",
            "profile": "प्रोफ़ाइल",
            "total_orders": "कुल आदेश",
            "total_spent": "कुल खर्च",
            "saved": "बचत",
            "trusted_users": "विश्वसनीय उपयोगकर्ता",
            "recent_orders": "हाल के आदेश",
            "our_services": "हमारी सेवाएं और मूल्य",
            "service_type": "सेवा का प्रकार",
            "single_side": "एक तरफ",
            "double_side": "दोनों तरफ",
            "bulk_print": "थोक (>100 पेज)",
            "bw_print": "ब्लैक एंड व्हाइट प्रिंट",
            "bw_xerox": "जेरोक्स (ब्लैक एंड व्हाइट)",
            "color_print": "कलर प्रिंट / जेरोक्स",
            "color_glossy": "कलर प्रिंट (चमकदार)",
            "spiral": "सर्पिल बाइंडिंग",
            "glass_binding": "ग्लास शीट बाइंडिंग",
            "account_settings": "खाता सेटिंग्स",
            "update_pass_desc": "अपना पासवर्ड अपडेट करें या अपने खाते का विवरण प्रबंधित करें।",
            "go_profile": "पूर्ण प्रोफ़ाइल सेटिंग्स पर जाएं",
            "no_orders": "कोई आदेश नहीं मिला। अपना पहला प्रिंट शुरू करें!",
            "newOrder": "नया आदेश",
            "amount": "राशि",
            "pages": "पृष्ठ",
            "downloadInvoice": "चालान डाउनलोड करें",
            "personal_info": "व्यक्तिगत जानकारी",
            "email_addr": "ईमेल पता",
            "mobile_num": "मोबाइल नंबर",
            "order_history": "आर्डर इतिहास",
            "change_pass": "पासवर्ड बदलें",
            "current_pass": "वर्तमान पासवर्ड",
            "new_pass": "नया पासवर्ड",
            "update_pass_btn": "पासवर्ड अपडेट करें",
            "security": "सुरक्षा",
            "my_details": "मेरा विवरण",
            "my_orders": "मेरे आदेश",
            "new_print_order": "नया प्रिंट ऑर्डर",
            "click_upload": "दस्तावेज़ अपलोड करने के लिए क्लिक करें",
            "pages_count": "पेज मिले",
            "print_type": "प्रिंट प्रकार",
            "bw_option": "ब्लैक एंड व्हाइट",
            "color_option": "रंगीन",
            "copies": " प्रतियां",
            "total_estimate": "कुल अनुमान",
            "proceed_payment": "भुगतान के लिए आगे बढ़ें",
            "payment_success": "भुगतान सफल!",
            "order_processing": "आपका आदेश संसाधित किया जा रहा है।",
            "complete_payment": "भुगतान पूरा करें",
            "scan_pay": "पुष्टि करने के लिए स्कैन करें और 50% भुगतान करें",
            "order_total": "जुमला रक़म",
            "pay_now": "अभी भुगतान करें (50%)",
            "i_have_paid": "मैंने भुगतान किया है",
            "cancel_order": "आदेश रद्द करें",
            "plus_3_week": "+3 इस सप्ताह",
            "secure_100": "100% सुरक्षित",
            "students_count": "1,200+ छात्र",
            "create_first_order": "पहला आदेश बनाएं",
            "history_appear_here": "आपका प्रिंटिंग इतिहास यहां दिखाई देगा। सेकंडों में अपना पहला प्रिंट शुरू करें!",
            "view_services": "सेवाएं देखें",
            "launching_soon": "जल्द आ रहा है",
            "rated_1": "#1 छात्र पसंद",
            "printing_reimagined": "प्रिंटिंग की नई परिभाषा.",
            "instant_smart": "तत्काल और स्मार्ट.",
            "hero_desc": "कहीं से भी दस्तावेज़ अपलोड करें, सुरक्षित भुगतान करें और सेकंडों में प्राप्त करें। कैंपस प्रिंटिंग का भविष्य यहां है।",
            "get_started": "अभी शुरू करें",
            "view_pricing": "मूल्य देखें",
            "printing_analytics": "प्रिंटिंग एनालिटिक्स",
            "total_savings": "कुल बचत",
            "plus_12_month": "+12% इस महीने",
            "active_orders": "सक्रिय आदेश",
            "pending": "लंबित",
            "unbeatable_pricing": "बेजोड़ मूल्य",
            "pricing_sub": "पारदर्शी लागत। कोई छिपी हुई फीस नहीं। छात्रों के लिए अनुकूल।",
            "front_page": "पहला पेज",
            "front_back": "आगे और पीछे",
            "lightning_fast": "बिजली की गति",
            "fast_desc": "ऑनलाइन ऑर्डर करें और दुकान पहुंचने से पहले ही प्राप्त करें।",
            "secure_payments": "सुरक्षित भुगतान",
            "secure_desc": "100% सुरक्षित क्यूआर कोड और यूपीआई भुगतान एकीकरण।",
            "anywhere_access": "कहीं भी पहुंच",
            "access_desc": "अपने फोन, लैपटॉप या टैबलेट से तुरंत फ़ाइलें अपलोड करें।",
            "add_items": "प्रिंट करने के लिए आइटम जोड़ें",
            "your_list": "आपकी ऑर्डर सूची",
            "pdf_module": "पीडीएफ मॉड्यूल",
            "doc_module": "दस्तावेज़ मॉड्यूल",
            "upload_pdf_title": "पीडीएफ अपलोड करें",
            "browse_files": "अपनी फ़ाइलें ब्राउज़ करने के लिए क्लिक करें",
            "preview": "पूर्वावलोकन",
            "edit_pages": "पृष्ठ संपादित करें",
            "manual_format": "मैनुअल फ़ార్मेटिंग",
            "manual_format_desc": "वर्ड दस्तावेज़ों को सही लेआउट सुनिश्चित करने के लिए मैनुअल प्रोसेसिंग की आवश्यकता होती है। कृपया व्हाट्सएप के माध्यम से सत्यापित करें।",
            "chat_whatsapp": "व्हाट्सएप पर चैट करें",
            "special_instr": "विशेष निर्देश",
            "instr_placeholder": "जैसे सर्पिल बाइंडिंग, लैमिनेशन, केवल विषम पृष्ठ प्रिंट करें...",
            "advance_pay_label": "भुगतान करने के लिए अग्रिम (50%)",
            "submit_pay": "जमा करें और भुगतान करें",
            "premium_services": "प्रीमियम सेवाएं",
            "word_docs": "वर्ड दस्तावेज़",
            "word_coming_soon": "अपलोड, संपादन और कनवर्टर सुविधाएँ हैं",
            "live_pdf_editor": "लाइव पीडीएफ संपादक",
            "live_editor_desc": "बाहरी उपकरणों की कोई आवश्यकता नहीं है। अवांछित पृष्ठों को हटा दें, ओरिएंटेशन घुमाएं, और अपने दस्तावेज़ को यहीं हमारे टैब में अंतिम रूप दें।",
            "digital_deliver": "डिजिटल डिलीवरी",
            "digital_desc": "अपने भौतिक प्रिंट के साथ डिजिटल प्रतियां प्राप्त करें। हम आसान पुन: आदेश देने के लिए आपके महत्वपूर्ण दस्तावेजों को सुरक्षित रूप से संग्रहीत करते हैं।",
            "quality_quote": "\"जहां गुणवत्ता गति से मिलती है\"",
            "new_feature": "नई सुविधा",
            "contact_support": "संपर्क और सहायता",
            "need_help_desc": "ऑर्डर के साथ मदद चाहिए? मैनुअल दस्तावेज़ स्वरूपण चाहते हैं? व्हाट्सएप पर सीधे हमारे साथ चैट करें।",
            "support_hours": "सहायता समय",
            "trust_secure": "100% सुरक्षित",
            "trust_secure_desc": "एन्क्रिप्टेड भुगतान और डेटा गोपनीयता",
            "trust_fast": "बिजली की गति",
            "trust_fast_desc": "24 घंटे वितरण की गारंटी",
            "trust_quality": "सर्वोत्तम गुणवत्ता",
            "trust_quality_desc": "प्रीमियम कागज और स्पष्ट प्रिंट",
            "spending_analysis": "खर्च विश्लेषण",
            "last_7_days": "पिछले 7 दिन",
            "daily_quote": "दैनिक प्रेरणा",
            "design_quote": "डिज़ाइन केवल वह नहीं है जो दिखता है और महसूस होता है। डिज़ाइन यह है कि यह कैसे काम करता है।",
            "lic_footer": "स्मार्ट ज़ेरॉक्स एंड कंपनी द्वारा लाइसेन्स प्राप्त \u00A9 2024",
            "made_with_love": "छात्रों के लिए \u2764\uFE0F के साथ बनाया गया",
            "morning_express": "मॉर्निंग एक्सप्रेस",
            "morning_desc": "सुबह 8 बजे से पहले ऑर्डर करें, 10:30 बजे प्राप्त करें।",
            "live_pdf_desc": "तुरंत पृष्ठ संपादित करें, घुमाएं, हटाएं।",
            "glass_binding": "ग्लास शीट बाइंडिंग",
            "glass_desc": "प्रीमियम बाइंडिंग अब उपलब्ध है।",
            "conditions_apply": "शर्तें लागू",
            "track_latest": "लाइव स्थिति: नवीनतम आदेश",
            "quote_1": "तकनीक सबसे अच्छी तब होती है जब वह लोगों को एक साथ लाती है।",
            "quote_author_1": "मैट मुलेनवेग",
            "quote_2": "यह कोई बग नहीं है, यह एक विशेषता है।",
            "quote_author_2": "अज्ञात",
            "quote_3": "बातें सस्ती हैं। मुझे कोड दिखाओ।",
            "quote_author_3": "लिनस टॉर्वाल्ड्स",
            "quote_4": "सादगी दक्षता की आत्मा है।",
            "quote_author_4": "ऑस्टिन फ्रीमैन",
            "quote_5": "भूखे रहो, मूर्ख रहो।",
            "quote_author_5": "स्टीव जॉब्स"
        }
    },
    kn: {
        translation: {
            "welcome": "ಸ್ವಾಗತ",
            "login_title": "ಮತ್ತೆ ಸ್ವಾಗತ",
            "signup_title": "ಖಾತೆಯನ್ನು ರಚಿಸಿ",
            "subtitle_login": "ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ",
            "subtitle_signup": "ಸ್ಮಾರ್ಟ್ ಪ್ರಿಂಟಿಂಗ್‌ಗಾಗಿ ಸೇರಿಕೊಳ್ಳಿ",
            "mobile": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
            "name": "ಪೂರ್ಣ ಹೆಸರು",
            "otp": "OTP ನಮೂದಿಸಿ",
            "send_otp": "OTP ಕಳುಹಿಸಿ",
            "verify_otp": "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್",
            "verify_signup": "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸೈನ್ ಅಪ್",
            "google_login": "Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ",
            "home": "ಮುಖಪುಟ",
            "dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            "logout": "ಲಾಗ್ ಔಟ್",
            "login": "ಲಾಗಿನ್",
            "signup": "ಸೈನ್ ಅಪ್",
            "brand_name": "ಸ್ಮಾರ್ಟ್ ಜೆರಾಕ್ಸ್",
            "nav_dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            "nav_login": "ಲಾಗಿನ್",
            "nav_signup": "ಸೈನ್ ಅಪ್",
            "nav_logout": "ಲಾಗ್ ಔಟ್",
            "nav_profile": "ಪ್ರೊಫೈಲ್",
            "create_account": "ಖಾತೆಯನ್ನು ರಚಿಸಿ",
            "welcome_back": "ಮತ್ತೆ ಸ್ವಾಗತ",
            "signup_subtitle": "ಅತ್ಯುತ್ತಮ ಪ್ರಿಂಟಿಂಗ್ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ",
            "login_subtitle": "ನಿಮ್ಮ ಅನುಭವವನ್ನು ಮುಂದುವರಿಸಿ",
            "confirm_pass": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
            "login_btn": "ಸೈನ್ ಇನ್",
            "already_account": "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
            "no_account": "ಖಾತೆ ಇಲ್ಲವೇ?",
            "demo_otp": "ಡೆಮೊಗೆ 1234 ಬಳಸಿ",
            "overview": "ಅವಲೋಕನ",
            "services": "ಸೇವೆಗಳು",
            "support": "ಬೆಂಬಲ",
            "profile": "ಪ್ರೊಫೈಲ್",
            "total_orders": "ಒಟ್ಟು ಆದೇಶಗಳು",
            "total_spent": "ಒಟ್ಟು ಖರ್ಚು",
            "saved": "ಉಳಿಸಲಾಗಿದೆ",
            "trusted_users": "ವಿಶ್ವಾಸಾರ್ಹ ಬಳಕೆದಾರರು",
            "recent_orders": "ಇತ್ತೀಚಿನ ಆದೇಶಗಳು",
            "our_services": "ನಮ್ಮ ಸೇವೆಗಳು ಮತ್ತು ದರಗಳು",
            "service_type": "ಸೇವೆಯ ಪ್ರಕಾರ",
            "single_side": "ಒಂದು ಬದಿ",
            "double_side": "ಎರಡು ಬದಿ",
            "bulk_print": "ದೊಡ್ಡ ಪ್ರಮಾಣ (>100 ಪುಟಗಳು)",
            "bw_print": "ಬ್ಲ್ಯಾಕ್ & ವೈಟ್ ಪ್ರಿಂಟ್",
            "bw_xerox": "ಜೆರಾಕ್ಸ್ (ಕಪ್ಪು ಮತ್ತು ಬಿಳಿ)",
            "color_print": "ಬಣ್ಣದ ಮುದ್ರಣ (ಸ್ಟ್ಯಾಂಡರ್ಡ್)",
            "color_glossy": "ಬಣ್ಣದ ಮುದ್ರಣ (ಗ್ಲಾಸಿ)",
            "spiral": "ಸ್ಪೈರಲ್ ಬೈಂಡಿಂಗ್",
            "glass_binding": "ಗ್ಲಾಸ್ ಶೀಟ್ ಬೈಂಡಿಂಗ್",
            "account_settings": "ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
            "update_pass_desc": "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಅಥವಾ ಖಾತೆ ವಿವರಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
            "go_profile": "ಪೂರ್ಣ ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಿಗೆ ಹೋಗಿ",
            "no_orders": "ಆದೇಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ಪ್ರಿಂಟ್ ಪ್ರಾರಂಭಿಸಿ!",
            "newOrder": "ಹೊಸ ಆದೇಶ",
            "amount": "ಮೊತ್ತ",
            "pages": "ಪುಟಗಳು",
            "downloadInvoice": "ಇನ್ವಾಯ್ಸ್ ಡೌನ್‌ಲೋಡ್",
            "personal_info": "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
            "email_addr": "ಇಮೇಲ್ ವಿಳಾಸ",
            "mobile_num": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
            "order_history": "ಆದೇಶ ಇತಿಹಾಸ",
            "change_pass": "ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ",
            "current_pass": "ಪ್ರಸ್ತುತ ಪಾಸ್‌ವರ್ಡ್",
            "new_pass": "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್",
            "update_pass_btn": "ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ",
            "security": "ಭದ್ರತೆ",
            "my_details": "ನನ್ನ ವಿವರಗಳು",
            "my_orders": "ನನ್ನ ಆದೇಶಗಳು",
            "new_print_order": "ಹೊಸ ಪ್ರಿಂಟ್ ಆರ್ಡರ್",
            "click_upload": "ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
            "pages_count": "ಪುಟಗಳು ಕಂಡುಬಂದಿವೆ",
            "print_type": "ಮುದ್ರಣ ಪ್ರಕಾರ",
            "bw_option": "ಕಪ್ಪು ಮತ್ತು ಬಿಳಿ",
            "color_option": "ಬಣ್ಣ",
            "copies": " ಪ್ರತಿಗಳು",
            "total_estimate": "ಒಟ್ಟು ಅಂದಾಜು",
            "proceed_payment": "ಪಾವತಿಗೆ ಮುಂದುವರಿಯಿರಿ",
            "payment_success": "ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
            "order_processing": "ನಿಮ್ಮ ಆದೇಶವನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ.",
            "complete_payment": "ಪಾವತಿ ಪೂರ್ಣಗೊಳಿಸಿ",
            "scan_pay": "ದೃಢೀಕರಿಸಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಮತ್ತು 50% ಪಾವತಿಸಿ",
            "order_total": "ಒಟ್ಟು ಆದೇಶ",
            "pay_now": "ಈಗ ಪಾವತಿಸಿ (50%)",
            "i_have_paid": "ನಾನು ಪಾವತಿಸಿದ್ದೇನೆ",
            "cancel_order": "ಆದೇಶ ರದ್ದುಗೊಳಿಸಿ",
            "plus_3_week": "ಈ ವಾರ +3",
            "secure_100": "100% ಸುರಕ್ಷಿತ",
            "students_count": "1,200+ ವಿದ್ಯಾರ್ಥಿಗಳು",
            "create_first_order": "ಮೊದಲ ಆದೇಶವನ್ನು ರಚಿಸಿ",
            "history_appear_here": "ನಿಮ್ಮ ಮುದ್ರಣ ಇತಿಹಾಸ ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ. ಕೆಲವೇ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ನಿಮ್ಮ ಮೊದಲ ಮುದ್ರಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ!",
            "view_services": "ಸೇವೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
            "launching_soon": "ಶೀಘ್ರದಲ್ಲೇ ಪ್ರಾರಂಭವಾಗಲಿದೆ",
            "rated_1": "#1 ವಿದ್ಯಾರ್ಥಿ ಆಯ್ಕೆ",
            "printing_reimagined": "ಮುದ್ರಣದ ಹೊಸ ವ್ಯಾಖ್ಯಾನ.",
            "instant_smart": "ತತ್ಕ್ಷಣ ಮತ್ತು ಸ್ಮಾರ್ಟ್.",
            "hero_desc": "ಎಲ್ಲಿಂದಲಾದರೂ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ, ಸುರಕ್ಷಿತವಾಗಿ ಪಾವತಿಸಿ ಮತ್ತು ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಪಡೆಯಿರಿ. ಕ್ಯಾಂಪಸ್ ಮುದ್ರಣದ ಭವಿಷ್ಯ ಇಲ್ಲಿದೆ.",
            "get_started": "ಈಗಲೇ ಪ್ರಾರಂಭಿಸಿ",
            "view_pricing": "ದರ ಪಟ್ಟಿಯನ್ನು ವೀಕ್ಷಿಸಿ",
            "printing_analytics": "ಮುದ್ರಣ ವಿಶ್ಲೇಷಣೆ",
            "total_savings": "ಒಟ್ಟು ಉಳಿತಾಯ",
            "plus_12_month": "ಈ ತಿಂಗಳು +12%",
            "active_orders": "ಸಕ್ರಿಯ ಆದೇಶಗಳು",
            "pending": "ಬಾಕಿ ಇದೆ",
            "unbeatable_pricing": "ಅತ್ಯುತ್ತಮ ದರಗಳು",
            "pricing_sub": "ಪಾರದರ್ಶಕ ದರಗಳು. ಯಾವುದೇ ಗುಪ್ತ ಶುಲ್ಕಗಳಿಲ್ಲ. ವಿದ್ಯಾರ್ಥಿ ಸ್ನೇಹಿ.",
            "front_page": "ಮುಂದಿನ ಪುಟ",
            "front_back": "ಮುಂದೆ ಮತ್ತು ಹಿಂದೆ",
            "lightning_fast": "ಮಿಂಚಿನ ವೇಗ",
            "fast_desc": "ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಆರ್ಡರ್ ಮಾಡಿ ಮತ್ತು ಅಂಗಡಿಗೆ ತಲುಪುವ ಮೊದಲೇ ಸಂಗ್ರಹಿಸಿ.",
            "secure_payments": "ಸುರಕ್ಷಿತ ಪಾವತಿಗಳು",
            "secure_desc": "100% ಸುರಕ್ಷಿತ QR ಕೋಡ್ ಮತ್ತು UPI ಪಾವತಿ ಏಕೀಕರಣ.",
            "anywhere_access": "ಎಲ್ಲಿಂದಲಾದರೂ ಪ್ರವೇಶ",
            "access_desc": "ನಿಮ್ಮ ಫೋನ್, ಲ್ಯಾಪ್‌ಟಾಪ್ ಅಥವಾ ಟ್ಯಾಬ್ಲೆಟ್‌ನಿಂದ ತಕ್ಷಣ ಫೈಲ್‌ಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
            "add_items": "ಮುದ್ರಿಸಲು ಐಟಂಗಳನ್ನು ಸೇರಿಸಿ",
            "your_list": "ನಿಮ್ಮ ಆರ್ಡರ್ ಪಟ್ಟಿ",
            "pdf_module": "ಪಿಡಿಎಫ್ ಮಾಡ್ಯೂಲ್",
            "doc_module": "ಡಾಕ್ಯುಮೆಂಟ್ ಮಾಡ್ಯೂಲ್",
            "upload_pdf_title": "ಪಿಡಿಎಫ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
            "browse_files": "ನಿಮ್ಮ ಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
            "preview": "ಮುನ್ನೋಟ",
            "edit_pages": "ಪುಟಗಳನ್ನು ಎಡಿಟ್ ಮಾಡಿ",
            "manual_format": "ಮ್ಯಾನುಯಲ್ ಫಾರ್ಮ್ಯಾಟಿಂಗ್",
            "manual_format_desc": "ವರ್ಡ್ ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳಿಗೆ ಸರಿಯಾದ ಲೇಔಟ್ ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ಮ್ಯಾನುಯಲ್ ಪ್ರಕ್ರಿಯೆಯ ಅಗತ್ಯವಿದೆ. ದಯವಿಟ್ಟು ವಾಟ್ಸಾಪ್ ಮೂಲಕ ಪರಿಶೀಲಿಸಿ.",
            "chat_whatsapp": "ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಚಾಟ್ ಮಾಡಿ",
            "special_instr": "ವಿಶೇಷ ಸೂಚನೆಗಳು",
            "instr_placeholder": "ಉದಾ. ಸ್ಪೈರಲ್ ಬೈಂಡಿಂಗ್, ಲ್ಯಾಮಿನೇಶನ್, ಬೆಸ ಪುಟಗಳನ್ನು ಮಾತ್ರ ಪ್ರಿಂಟ್ ಮಾಡಿ...",
            "advance_pay_label": "ಪಾವತಿಸಲು ಮುಂಗಡ (50%)",
            "submit_pay": "ಸಲ್ಲಿಸಿ ಮತ್ತು ಪಾವತಿಸಿ",
            "premium_services": "ಪ್ರೀಮಿಯಂ ಸೇವೆಗಳು",
            "word_docs": "ವರ್ಡ್ ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳು",
            "word_coming_soon": "ಅಪ್‌ಲೋಡ್, ಎಡಿಟ್ ಮತ್ತು ಪರಿವರ್ತಕ ವೈಶಿಷ್ಟ್ಯಗಳು",
            "live_pdf_editor": "ಲೈವ್ ಪಿಡಿಎಫ್ ಎಡಿಟರ್",
            "live_editor_desc": "ಬಾಹ್ಯ ಪರಿಕರಗಳ ಅಗತ್ಯವಿಲ್ಲ. ಅನಗತ್ಯ ಪುಟಗಳನ್ನು ತೆಗೆದುಹಾಕಿ, ದೃಷ್ಟಿಕೋನವನ್ನು ತಿರುಗಿಸಿ ಮತ್ತು ನಮ್ಮ ಟ್ಯಾಬ್‌ನಲ್ಲಿಯೇ ನಿಮ್ಮ ಡಾಕ್ಯುಮೆಂಟ್ ಅನ್ನು ಅಂತಿಮಗೊಳಿಸಿ.",
            "digital_deliver": "ಡಿಜಿಟಲ್ ವಿತರಣೆ",
            "digital_desc": "ನಿಮ್ಮ ಭೌತಿಕ ಮುದ್ರಣಗಳ ಜೊತೆಗೆ ಡಿಜಿಟಲ್ ಪ್ರತಿಗಳನ್ನು ಪಡೆಯಿರಿ. ಸುಲಭ ಮರು-ಆದೇಶಕ್ಕಾಗಿ ನಾವು ನಿಮ್ಮ ಪ್ರಮುಖ ದಾಖಲೆಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸಂಗ್ರಹಿಸುತ್ತೇವೆ.",
            "quality_quote": "\"ಗುಣಮಟ್ಟವು ವೇಗವನ್ನು ಭೇಟಿಯಾಗುವಲ್ಲಿ\"",
            "new_feature": "ಹೊಸ ವೈಶಿಷ್ಟ್ಯ",
            "contact_support": "ಸಂಪರ್ಕ ಮತ್ತು ಬೆಂಬಲ",
            "need_help_desc": "ಆರ್ಡರ್ ಬಗ್ಗೆ ಸಹಾಯ ಬೇಕೇ? ಮ್ಯಾನುಯಲ್ ಡಾಕ್ಯುಮೆಂಟ್ ಫಾರ್ಮ್ಯಾಟಿಂಗ್ ಬೇಕೇ? ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ನಮ್ಮೊಂದಿಗೆ ನೇರವಾಗಿ ಚಾಟ್ ಮಾಡಿ.",
            "support_hours": "ಬೆಂಬಲ ಸಮಯ",
            "trust_secure": "100% ಸುರಕ್ಷಿತ",
            "trust_secure_desc": "ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾದ ಪಾವತಿಗಳು ಮತ್ತು ಡೇಟಾ ಗೌಪ್ಯತೆ",
            "trust_fast": "ಮಿಂಚಿನ ವೇಗ",
            "trust_fast_desc": "24 ಗಂಟೆಗಳ ವಿತರಣಾ ಗ್ಯಾರಂಟಿ",
            "trust_quality": "ಅತ್ಯುತ್ತಮ ಗುಣಮಟ್ಟ",
            "trust_quality_desc": "ಪ್ರೀಮಿಯಂ ಪೇಪರ್ ಮತ್ತು ಸ್ಫುಟವಾದ ಮುದ್ರಣಗಳು",
            "spending_analysis": "ಖರ್ಚು ವಿಶ್ಲೇಷಣೆ",
            "last_7_days": "ಕಳೆದ 7 ದಿನಗಳು",
            "daily_quote": "ದೈನಂದಿನ ಪ್ರೇರಣೆ",
            "design_quote": "ವಿನ್ಯಾಸವು ಕೇವಲ ನೋಟ ಮತ್ತು ಅನುಭವವಲ್ಲ. ವಿನ್ಯಾಸವು ಅದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂಬುದು.",
            "lic_footer": "ಸ್ಮಾರ್ಟ್ ಜೆರಾಕ್ಸ್ & ಕಂ ನಿಂದ ಪರವಾನಗಿ ಪಡೆದಿದೆ \u00A9 2024",
            "made_with_love": "ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ \u2764\uFE0F ನೊಂದಿಗೆ ಮಾಡಲಾಗಿದೆ",
            "morning_express": "ಮಾರ್ನಿಂಗ್ ಎಕ್ಸ್‌ಪ್ರೆಸ್",
            "morning_desc": "ಬೆಳಿಗ್ಗೆ 8 ಗಂಟೆಗೆ ಮೊದಲು ಆರ್ಡರ್ ಮಾಡಿ, 10:30 ಕ್ಕೆ ಪಡೆಯಿರಿ.",
            "live_pdf_desc": "ಪುಟಗಳನ್ನು ತಕ್ಷಣ ಎಡಿಟ್ ಮಾಡಿ, ತಿರುಗಿಸಿ.",
            "glass_binding": "ಗ್ಲಾಸ್ ಶೀಟ್ ಬೈಂಡಿಂಗ್",
            "glass_desc": "ಪ್ರೀಮಿಯಂ ಬೈಂಡಿಂಗ್ ಈಗ ಲಭ್ಯವಿದೆ.",
            "conditions_apply": "ಷರತ್ತುಗಳು ಅನ್ವಯಿಸುತ್ತವೆ",
            "track_latest": "ಲೈವ್ ಸ್ಥಿತಿ: ಇತ್ತೀಚಿನ ಆದೇಶ",
            "quote_1": "ತಂತ್ರಜ್ಞಾನವು ಜನರನ್ನು ಒಟ್ಟುಗೂಡಿಸಿದಾಗ ಉತ್ತಮವಾಗಿರುತ್ತದೆ.",
            "quote_author_1": "ಮ್ಯಾಟ್ ಮುಲ್ಲೆನ್ವೆಗ್",
            "quote_2": "ಇದು ಬಗ್ ಅಲ್ಲ, ಇದು ವೈಶಿಷ್ಟ್ಯ.",
            "quote_author_2": "ಅಜ್ಞಾತ",
            "quote_3": "ಮಾತು ಸುಲಭ. ಕೋಡ್ ತೋರಿಸಿ.",
            "quote_author_3": "ಲಿನಸ್ ಟೊರ್ವಾಲ್ಡ್ಸ್",
            "quote_4": "ಸರಳತೆ ದಕ್ಷತೆಯ ಆತ್ಮ.",
            "quote_author_4": "ಆಸ್ಟಿನ್ ಫ್ರೀಮನ್",
            "quote_5": "ಹಸಿದಿರಿ, ಮೂರ್ಖರಾಗಿರಿ.",
            "quote_author_5": "ಸ್ಟೀವ್ ಜಾಬ್ಸ್"
        }
    },
    bn: {
        translation: {
            "welcome": "স্বাগতম",
            "login_title": "স্বাগতম",
            "signup_title": "অ্যাকাউন্ট তৈরি করুন",
            "subtitle_login": "প্রিন্টিং চালিয়ে যেতে সাইন ইন করুন",
            "subtitle_signup": "স্মার্ট প্রিন্টিংয়ের জন্য আমাদের সাথে যোগ দিন",
            "mobile": "মোবাইল নম্বর",
            "login": "লগইন",
            "signup": "সাইন আপ",
            "brand_name": "স্মার্ট জেরক্স",
            "nav_dashboard": "ড্যাশবোর্ড",
            "nav_login": "লগইন",
            "nav_signup": "সাইন আপ",
            "nav_logout": "লগ আউট",
            "nav_profile": "প্রোফাইল",
            "create_account": "অ্যাকাউন্ট তৈরি করুন",
            "welcome_back": "স্বাগতম",
            "signup_subtitle": "স্মার্ট প্রিন্টিং নেটওয়ার্কে যোগ দিন",
            "login_subtitle": "আপনার অভিজ্ঞতা চালিয়ে যান",
            "confirm_pass": "পাসওয়ার্ড নিশ্চিত করুন",
            "login_btn": "সাইন ইন",
            "already_account": "ஏற்கனவே கணக்கு உள்ளதா?",
            "no_account": "கணக்கு இல்லையா?",
            "dashboard": "ড্যাশবোর্ড",
            "logout": "লগ আউট",
            "overview": "সংক্ষিপ্তসার",
            "services": "পরিষেবা",
            "support": "সহায়তা",
            "profile": "প্রোফাইল",
            "total_orders": "মোট অর্ডার",
            "total_spent": "মোট ব্যয়",
            "saved": "সংরক্ষিত",
            "trusted_users": "বিশ্বস্ত ব্যবহারকারী",
            "recent_orders": "সাম্প্রতিক অর্ডার",
            "our_services": "আমাদের পরিষেবা এবং মূল্য",
            "service_type": "পরিষেবার ধরণ",
            "single_side": "এক পাশ",
            "double_side": "উভয় পাশ",
            "bw_xerox": "জেরক্স (সাদা-কালো)",
            "bw_print": "সাদা-কালো প্রিন্ট",
            "color_print": "রঙিন প্রিন্ট",
            "spiral": "স্পাইরাল বাইন্ডিং",
            "glass_binding": "গ্লাস শিট বাইন্ডিং",
            "launching_soon": "শীঘ্রই আসছে",
            "no_orders": "কোনো অর্ডার পাওয়া যায়নি। আপনার প্রথম প্রিন্ট শুরু করুন!",
            "create_first_order": "প্রথম অর্ডার তৈরি করুন",
            "unbeatable_pricing": "অবিশ্বাস্য মূল্য",
            "secure_100": "১০০% নিরাপদ",
            "students_count": "১,২০০+ শিক্ষার্থী",
            "get_started": "এখনই শুরু করুন",
            "add_items": "প্রিন্ট করার জন্য আইটেম যোগ করুন",
            "your_list": "আপনার অর্ডার তালিকা",
            "pdf_module": "পিডিএফ মডিউল",
            "doc_module": "ডকুমেন্ট মডিউল",
            "upload_pdf_title": "পিডিএফ আপলোড করুন",
            "browse_files": "ফাইল ব্রাউজ করতে ক্লিক করুন",
            "preview": "প্রিভিউ",
            "edit_pages": "পেজ এডিট করুন",
            "manual_format": "ম্যানুয়াল ফরম্যাটিং",
            "manual_format_desc": "ওয়ার্ড ডকুমেন্টের সঠিক লেআউট নিশ্চিত করতে ম্যানুয়াল প্রসেসিং প্রয়োজন। দয়া করে হোয়াটসঅ্যাপে যাচাই করুন।",
            "chat_whatsapp": "হোয়াটসঅ্যাপে চ্যাট করুন",
            "special_instr": "বিশেষ নির্দেশাবলী",
            "instr_placeholder": "যেমন স্পাইরাল বাইন্ডিং, ল্যামিনেশন, শুধুমাত্র বিজোড় পেজ প্রিন্ট করুন...",
            "advance_pay_label": "অগ্রিম পেমেন্ট (৫০%)",
            "submit_pay": "জমা দিন এবং পেমেন্ট করুন",
            "premium_services": "প্রিমিয়াম পরিষেবা",
            "word_docs": "ওয়ার্ড ডকুমেন্ট",
            "word_coming_soon": "আপলোড, এডিট এবং কনভার্টার ফিচার",
            "live_pdf_editor": "লাইভ পিডিএফ এডিটর",
            "live_editor_desc": "বাইরের টুলের প্রয়োজন নেই। অপ্রয়োজনীয় পেজ সরান, ওরিয়েন্টেশন ঘোরান এবং আমাদের ট্যাবেই আপনার ডকুমেন্ট চূড়ান্ত করুন।",
            "digital_deliver": "ডিজিটাল ডেলিভারি",
            "digital_desc": "আপনার ফিজিক্যাল প্রিন্টের পাশাপাশি ডিজিটাল কপি পান। সহজে পুনরায় অর্ডার করার জন্য আমরা আপনার গুরুত্বপূর্ণ ডকুমেন্ট নিরাপদে সংরক্ষণ করি।",
            "quality_quote": "\"যেখানে গুণমান গতির সাথে মিলিত হয়\"",
            "new_feature": "নতুন বৈশিষ্ট্য",
            "contact_support": "যোগাযোগ এবং সহায়তা",
            "need_help_desc": "অর্ডার নিয়ে সাহায্য প্রয়োজন? ম্যানুয়াল ডকুমেন্ট ফরম্যাটিং চান? সরাসরি হোয়াটসঅ্যাপে আমাদের সাথে চ্যাট করুন।",
            "support_hours": "সহায়তা সময়",
            "trust_secure": "100% নিরাপদ",
            "trust_secure_desc": "এনক্রিপ্ট করা পেমেন্ট এবং ডেটা গোপনীয়তা",
            "trust_fast": "বজ্রগতি",
            "trust_fast_desc": "24 ঘন্টা ডেলিভারি গ্যারান্টি",
            "trust_quality": "সেরা গুণমান",
            "trust_quality_desc": "প্রিমিয়াম কাগজ এবং পরিষ্কার প্রিন্ট",
            "spending_analysis": "ব্যয় বিশ্লেষণ",
            "last_7_days": "গত 7 দিন",
            "daily_quote": "দৈনিক অনুপ্রেরণা",
            "design_quote": "ডিজাইন শুধু দেখতে কেমন বা কেমন অনুভব হয় তা নয়। ডিজাইন হলো এটি কীভাবে কাজ করে।",
            "lic_footer": "স্মার্ট জেরক্স অ্যান্ড কোং দ্বারা লাইসেন্সপ্রাপ্ত \u00A9 2024",
            "made_with_love": "শিক্ষার্থীদের জন্য \u2764\uFE0F দিয়ে তৈরি",
            "morning_express": "মর্নিং এক্সপ্রেস",
            "morning_desc": "সকাল ৮টার আগে অর্ডার করুন, ১০:৩০ এ পান।",
            "live_pdf_desc": "তাত্ক্ষণিকভাবে পেজ এডিট করুন, ঘোরান।",
            "glass_binding": "গ্লাস শিট বাইন্ডিং",
            "glass_desc": "প্রিমিয়াম বাইন্ডিং এখন উপলব্ধ।",
            "conditions_apply": "শর্তাবলী প্রযোজ্য",
            "track_latest": "লাইভ স্ট্যাটাস: সর্বশেষ অর্ডার",
            "quote_1": "প্রযুক্তি সেরা যখন এটি মানুষকে একত্রিত করে।",
            "quote_author_1": "ম্যাট মুলেনওয়েগ",
            "quote_2": "এটি কোনো বাগ নয়, এটি একটি বৈশিষ্ট্য।",
            "quote_author_2": "অজানা",
            "quote_3": "কথা বলা সস্তা। আমাকে কোড দেখান।",
            "quote_author_3": "লিনাস টরভাল্ডস",
            "quote_4": "সরলতা হলো দক্ষতার আত্মা।",
            "quote_author_4": "অস্টিন ফ্রিম্যান",
            "quote_5": "ক্ষুধার্ত থাকুন, বোকা থাকুন।",
            "quote_author_5": "স্টিভ জবস"
        }
    },
    te: {
        translation: {
            "welcome": "స్వాగతం",
            "login_title": "తిరిగి స్వాగతం",
            "signup_title": "ఖాతాను సృష్టించండి",
            "subtitle_login": "ప్రింటింగ్ కొనసాగించడానికి సైన్ ఇన్ చేయండి",
            "subtitle_signup": "స్మార్ట్ ప్రింటింగ్ కోసం మాతో చేరండి",
            "mobile": "మొబైల్ నంబర్",
            "login": "లాగిన్",
            "signup": "సైన్ అప్",
            "brand_name": "స్మార్ట్ జిరాక్స్",
            "nav_dashboard": "డాష్‌ బోర్డ్",
            "nav_login": "లాగిన్",
            "nav_signup": "సైన్ అప్",
            "nav_logout": "లాగ్ అవుట్",
            "nav_profile": "ప్రొఫైల్",
            "create_account": "ఖాతాను సృష్టించండి",
            "welcome_back": "తిరిగి స్వాగతం",
            "signup_subtitle": "స్మార్ట్ ప్రింటింగ్ నెట్‌వర్క్‌లో చేరండి",
            "login_subtitle": "మీ అనుభవాన్ని కొనసాగించండి",
            "confirm_pass": "పాస్‌వర్డ్‌ను నిర్ధారించండి",
            "login_btn": "సైన్ ఇన్",
            "already_account": "ఇప్పటికే ఖాతా ఉందా?",
            "no_account": "ఖాతా లేదా?",
            "dashboard": "డాష్‌ బోర్డ్",
            "logout": "లాగ్ అవుట్",
            "overview": "అవలోకనం",
            "services": "సేవలు",
            "support": "మద్దతు",
            "profile": "ప్రొఫైల్",
            "total_orders": "మొత్తం ఆర్డర్లు",
            "total_spent": "మొత్తం ఖర్చు",
            "saved": "ఆదా",
            "trusted_users": "విశ్వసనీయ వినియోగదారులు",
            "recent_orders": "ఇటీవలి ఆర్డర్లు",
            "our_services": "మా సేవలు & ధరలు",
            "service_type": "సేవ రకం",
            "single_side": "ఒక వైపు",
            "double_side": "డబుల్ సైడ్",
            "bw_xerox": "జిరాక్స్ (B&W)",
            "bw_print": "ప్రింట్‌అవుట్‌లు (B&W)",
            "color_print": "కలర్ ప్రింట్",
            "spiral": "స్పైరల్ బైండింగ్",
            "glass_binding": "గ్లాస్ షీట్ బైండింగ్",
            "launching_soon": "త్వరలో వస్తుంది",
            "no_orders": "ఆర్డర్లు ఏమీ లేవు. మీ మొదటి ప్రింట్‌ను ప్రారంభించండి!",
            "create_first_order": "మొదటి ఆర్డర్‌ని సృష్టించండి",
            "unbeatable_pricing": "సాటిలేని ధరలు",
            "secure_100": "100% సురక్షితం",
            "students_count": "1,200+ విద్యార్థులు",
            "get_started": "ఇప్పుడే ప్రారంభించండి",
            "add_items": "ప్రింట్ చేయడానికి అంశాలను జోడించండి",
            "your_list": "మీ ఆర్డర్ జాబితా",
            "pdf_module": "PDF మాడ్యూల్",
            "doc_module": "డాక్యుమెంట్ మాడ్యూల్",
            "upload_pdf_title": "PDF అప్‌లోడ్ చేయండి",
            "browse_files": "మీ ఫైళ్లను బ్రౌజ్ చేయడానికి క్లిక్ చేయండి",
            "preview": "ప్రివ్యూ",
            "edit_pages": "పేజీలను సవరించండి",
            "manual_format": "మాన్యువల్ ఫార్మాటింగ్",
            "manual_format_desc": "వర్డ్ డాక్యుమెంట్‌లకు సరైన లేఅవుట్ కోసం మాన్యువల్ ప్రాసెసింగ్ అవసరం. దయచేసి వాట్సాప్‌లో ధృవీకరించండి.",
            "chat_whatsapp": "వాట్సాప్‌లో చాట్ చేయండి",
            "special_instr": "ప్రత్యేక సూచనలు",
            "instr_placeholder": "ఉదా. స్పైరల్ బైండింగ్, లామినేషన్, బేసి పేజీలను మాత్రమే ప్రింట్ చేయండి...",
            "advance_pay_label": "చెల్లించడానికి అడ్వాన్స్ (50%)",
            "submit_pay": "సమర్పించండి మరియు చెల్లించండి",
            "premium_services": "ప్రీమియం సేవలు",
            "word_docs": "వర్డ్ డాక్యుమెంట్లు",
            "word_coming_soon": "అప్‌లోడ్, ఎడిట్ మరియు కన్వర్టర్ ఫీచర్లు",
            "live_pdf_editor": "లైవ్ PDF ఎడిటర్",
            "live_editor_desc": "బాహ్య టూల్స్ అవసరం లేదు. అవాంఛిత పేజీలను తొలగించండి, ఓరియంటేషన్‌ను తిప్పండి మరియు మా ట్యాబ్‌లోనే మీ డాక్యుమెంట్‌ను ఖరారు చేయండి.",
            "digital_deliver": "డిజిటల్ డెలివరీ",
            "digital_desc": "మీ భౌతిక ప్రింట్‌లతో పాటు డిజిటల్ కాపీలను పొందండి. సులభంగా రీ-ఆర్డర్ చేయడానికి మేము మీ ముఖ్యమైన డాక్యుమెంట్‌లను సురక్షితంగా నిల్వ చేస్తాము.",
            "quality_quote": "\"నాణ్యత వేగంతో కలిసే చోట\"",
            "new_feature": "కొత్త ఫీచర్",
            "contact_support": "సంప్రదించండి & మద్దతు",
            "need_help_desc": "ఆర్డర్‌తో సహాయం కావాలా? మాన్యువల్ డాక్యుమెంట్ ఫార్మాటింగ్ కావాలా? నేరుగా వాట్సాప్‌లో మాతో చాట్ చేయండి.",
            "support_hours": "మద్దతు గంటలు",
            "trust_secure": "100% సురక్షితం",
            "trust_secure_desc": "ఎన్‌క్రిప్టెడ్ చెల్లింపులు & డేటా గోప్యత",
            "trust_fast": "మెరుపు వేగం",
            "trust_fast_desc": "24 గంటల డెలివరీ హామీ",
            "trust_quality": "ఉత్తమ నాణ్యత",
            "trust_quality_desc": "ప్రీమియం పేపర్ & స్పష్టమైన ప్రింట్లు",
            "spending_analysis": "ఖర్చు విశ్లేషణ",
            "last_7_days": "గత 7 రోజులు",
            "daily_quote": "రోజువారీ ప్రేరణ",
            "design_quote": "డిజైన్ అంటే కేవలం చూడటానికి ఎలా ఉంది అనేది కాదు. డిజైన్ అంటే అది ఎలా పనిచేస్తుంది అనేది.",
            "lic_footer": "స్మార్ట్ జిరాక్స్ & కో ద్వారా లైసెన్స్ పొందింది \u00A9 2024",
            "made_with_love": "విద్యార్థుల కోసం \u2764\uFE0F తో రూపొందించబడింది",
            "morning_express": "మార్నింగ్ ఎక్స్‌ప్రెస్",
            "morning_desc": "ఉదయం 8 లోపు ఆర్డర్ చేయండి, 10:30 కి పొందండి.",
            "live_pdf_desc": "పేజీలను తక్షణమే సవరించండి, తిప్పండి.",
            "glass_binding": "గ్లాస్ షీట్ బైండింగ్",
            "glass_desc": "ప్రీమియం బైండింగ్ ఇప్పుడు అందుబాటులో ఉంది.",
            "conditions_apply": "షరతులు వర్తిస్తాయి",
            "track_latest": "లైవ్ స్థితి: తాజా ఆర్డర్",
            "quote_1": "టెక్నాలజీ ప్రజలను కలుపుతున్నప్పుడు ఉత్తమంగా ఉంటుంది.",
            "quote_author_1": "మాట్ ముల్లెన్వెగ్",
            "quote_2": "ఇది బగ్ కాదు, ఇది ఫీచర్.",
            "quote_author_2": "తెలియదు",
            "quote_3": "మాటలు చౌక. నాకు కోడ్ చూపించు.",
            "quote_author_3": "లినస్ టోర్వాల్డ్స్",
            "quote_4": "సరళత సామర్థ్యానికి ఆత్మ.",
            "quote_author_4": "ఆస్టిన్ ఫ్రీమాన్",
            "quote_5": "ఆకలితో ఉండండి, మూర్ఖంగా ఉండండి.",
            "quote_author_5": "స్టీవ్ జాబ్స్"
        }
    },
    mr: {
        translation: {
            "welcome": "स्वागत आहे",
            "login_title": "पुन्हा स्वागत आहे",
            "signup_title": "खाते तयार करा",
            "subtitle_login": "प्रिंटिंग सुरू ठेवण्यासाठी साइन इन करा",
            "subtitle_signup": "स्मार्ट प्रिंटिंगसाठी आमच्यात सामील व्हा",
            "mobile": "मोबाइल नंबर",
            "login": "लॉगिन",
            "signup": "साइन अप",
            "brand_name": "स्मार्ट झेरॉक्स",
            "nav_dashboard": "डॅशबोर्ड",
            "nav_login": "लॉगिन",
            "nav_signup": "साइन अप",
            "nav_logout": "लॉगआउट",
            "nav_profile": "प्रोफाइल",
            "create_account": "खाते तयार करा",
            "welcome_back": "पुन्हा स्वागत आहे",
            "signup_subtitle": "स्मार्ट प्रिंटिंग नेटवर्कमध्ये सामील व्हा",
            "login_subtitle": "तुमचा अनुभव सुरू ठेवा",
            "confirm_pass": "पासवर्डची पुष्टी करा",
            "login_btn": "साइन इन",
            "already_account": "आधीच खाते आहे का?",
            "no_account": "खाते नाही?",
            "dashboard": "डॅशबोर्ड",
            "logout": "लॉगआउट",
            "overview": "आढावा",
            "services": "सेवा",
            "support": "समर्थन",
            "profile": "प्रोफाइल",
            "total_orders": "एकूण ऑर्डर्स",
            "total_spent": "एकूण खर्च",
            "saved": "बचत",
            "trusted_users": "विश्वासार्ह वापरकर्ते",
            "recent_orders": "अलीकडील ऑर्डर्स",
            "our_services": "आमच्या सेवा आणि दर",
            "service_type": "सेवा प्रकार",
            "single_side": "एका बाजूला",
            "double_side": "दोन्ही बाजूला",
            "bw_xerox": "झेरॉक्स (ब्लॅक अँड व्हाईट)",
            "bw_print": "प्रिंटआउट (ब्लॅक अँड व्हाईट)",
            "color_print": "कलर प्रिंट",
            "spiral": "स्पायरल बाइंडिंग",
            "glass_binding": "ग्लास शीट बाइंडिंग",
            "launching_soon": "लवकरच येत आहे",
            "no_orders": "कोणत्याही ऑर्डर्स आढळल्या नाहीत. तुमची पहिली प्रिंट सुरू करा!",
            "create_first_order": "पहिली ऑर्डर तयार करा",
            "unbeatable_pricing": "अतुलनीय दर",
            "secure_100": "100% सुरक्षित",
            "students_count": "1,200+ विद्यार्थी",
            "get_started": "आता सुरू करा",
            "pdf_module": "पीडीएफ मॉड्यूल",
            "doc_module": "दस्तऐवज मॉड्यूल",
            "upload_pdf_title": "पीडीएफ अपलोड करा",
            "browse_files": "तुमच्या फाइल्स ब्राउझ करण्यासाठी क्लिक करा",
            "preview": "पूर्वावलोकन",
            "edit_pages": "पृष्ठे संपादित करा",
            "manual_format": "मॅन्युअल फॉरमॅटिंग",
            "manual_format_desc": "वर्ड दस्तऐवजांना योग्य मांडणी सुनिश्चित करण्यासाठी मॅन्युअल प्रक्रियेची आवश्यकता असते. कृपया व्हॉट्सअॅपद्वारे सत्यापित करा.",
            "chat_whatsapp": "व्हॉट्सअॅपवर चॅट करा",
            "special_instr": "विशेष सूचना",
            "instr_placeholder": "उदा. स्पायरल बाइंडिंग, लॅमिनेशन, फक्त विषम पृष्ठे प्रिंट करा...",
            "advance_pay_label": "भरण्यासाठी ऍडव्हान्स (५०%)",
            "submit_pay": "सबमिट करा आणि पैसे भरा",
            "premium_services": "प्रीमियम सेवा",
            "word_docs": "वर्ड दस्तऐवज",
            "word_coming_soon": "अपलोड, संपादन आणि कन्व्हर्टर वैशिष्ट्ये",
            "live_pdf_editor": "लाइव्ह पीडीएफ संपादक",
            "live_editor_desc": "बाह्य साधनांची आवश्यकता नाही. नको असलेली पृष्ठे काढून टाका, ओरिएंटेशन फिरवा आणि आमच्या टॅबमध्येच तुमचा दस्तऐवज अंतिम करा.",
            "digital_deliver": "डिजिटल डिलिव्हरी",
            "digital_desc": "तुमच्या भौतिक प्रिंट्ससह डिजिटल प्रती मिळवा. सोप्या री-ऑर्डरसाठी आम्ही तुमचे महत्त्वाचे दस्तऐवज सुरक्षितपणे साठवतो.",
            "quality_quote": "\"जिथे गुणवत्ता गतीला भेटते\"",
            "new_feature": "नवीन वैशिष्ट्य",
            "contact_support": "संपर्क आणि समर्थन",
            "need_help_desc": "ऑर्डरमध्ये मदत हवी आहे? मॅन्युअल दस्तऐवज फॉरमॅटिंग हवे आहे? व्हॉट्सअॅपवर थेट आमच्याशी चॅट करा.",
            "support_hours": "समर्थन वेळ",
            "trust_secure": "100% सुरक्षित",
            "trust_secure_desc": "एनक्रिप्टेड पेमेंट्स आणि डेटा गोपनीयता",
            "trust_fast": "विजेचा वेग",
            "trust_fast_desc": "24 तास डिलिव्हरी हमी",
            "trust_quality": "सर्वोत्तम गुणवत्ता",
            "trust_quality_desc": "प्रीमियम पेपर आणि स्पष्ट प्रिंट्स",
            "spending_analysis": "खर्च विश्लेषण",
            "last_7_days": "गेल्या 7 दिवसात",
            "daily_quote": "दैनिक प्रेरणा",
            "design_quote": "डिझाइन म्हणजे फक्त ते कसे दिसते आणि वाटते असे नाही. डिझाइन म्हणजे ते कसे कार्य करते.",
            "lic_footer": "स्मार्ट झेरॉक्स अँड कंपनी द्वारे परवानाकृत \u00A9 2024",
            "made_with_love": "विद्यार्थ्यांसाठी \u2764\uFE0F सह बनवले",
            "morning_express": "मॉर्निंग एक्सप्रेस",
            "morning_desc": "सकाळी 8 पूर्वी ऑर्डर करा, 10:30 ला मिळवा.",
            "live_pdf_desc": "लगेच पृष्ठे संपादित करा, फिरवा.",
            "glass_binding": "ग्लास शीट बाइंडिंग",
            "glass_desc": "प्रीमियम बाइंडिंग आता उपलब्ध आहे.",
            "conditions_apply": "अटी लागू",
            "track_latest": "लाइव्ह स्थिती: नवीनतम ऑर्डर",
            "quote_1": "तंत्रज्ञान तेव्हाच सर्वोत्तम असते जेव्हा ते लोकांना एकत्र आणते.",
            "quote_author_1": "मॅट मुलेनवेग",
            "quote_2": "हा बग नाही, हे वैशिष्ट्य आहे.",
            "quote_author_2": "अज्ञात",
            "quote_3": "बोलणे स्वस्त आहे. मला कोड दाखवा.",
            "quote_author_3": "लिनस टॉर्व्हॉल्ड्स",
            "quote_4": "साधेपणा हा कार्यक्षमतेचा आत्मा आहे.",
            "quote_author_4": "ऑस्टिन फ्रीमॅन",
            "quote_5": "भुकेले रहा, मूर्ख रहा.",
            "quote_author_5": "स्टीव्ह जॉब्स"
        }
    },
    ta: {
        translation: {
            "welcome": "வணக்கம்",
            "login_title": "நல்வரவு",
            "signup_title": "கணக்கை உருவாக்கவும்",
            "subtitle_login": "அச்சிடுவதைத் தொடர உள்நுழையவும்",
            "subtitle_signup": "ஸ்மார்ட் பிரிண்டிங்கிற்கு எங்களுடன் இணையுங்கள்",
            "mobile": "அலைபேசி எண்",
            "login": "உள்நுழைய",
            "signup": "பதிவு செய்க",
            "brand_name": "ஸ்மார்ட் ஜெராக்ஸ்",
            "nav_dashboard": "டாஷ்போர்டு",
            "nav_login": "உள்நுழைய",
            "nav_signup": "பதிவு செய்க",
            "nav_logout": "வெளியேறு",
            "nav_profile": "சுயவிவரம்",
            "create_account": "கணக்கை உருவாக்கவும்",
            "welcome_back": "நல்வரவு",
            "signup_subtitle": "ஸ்மார்ட் பிரிண்டிங் நெட்வொர்க்கில் இணையுங்கள்",
            "login_subtitle": "உங்கள் அனுபவத்தைத் தொடரவும்",
            "confirm_pass": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
            "login_btn": "உள்நுழைய",
            "already_account": "ஏற்கனவே கணக்கு உள்ளதா?",
            "no_account": "கணக்கு இல்லையா?",
            "dashboard": "டாஷ்போர்டு",
            "logout": "வெளியேறு",
            "overview": "கண்ணோட்டம்",
            "services": "சேவைகள்",
            "support": "ஆதரவு",
            "profile": "சுயவிவரம்",
            "total_orders": "மொத்த ஆர்டர்கள்",
            "total_spent": "மொத்த செலவு",
            "saved": "சேமிக்கப்பட்டது",
            "trusted_users": "நம்பகமான பயனர்கள்",
            "recent_orders": "சமீபத்திய ஆர்டர்கள்",
            "our_services": "எங்கள் சேவைகள் & விலை",
            "service_type": "சேவை வகை",
            "single_side": "ஒரு பக்கம்",
            "double_side": "இரண்டு பக்கம்",
            "bw_xerox": "ஜெராக்ஸ் (B&W)",
            "bw_print": "பிரிண்ட்அவுட் (B&W)",
            "color_print": "வண்ண பிரிண்ட்",
            "spiral": "சுருள் பிணைப்பு",
            "glass_binding": "கண்ணாடி தாள் பிணைப்பு",
            "launching_soon": "விரைவில் வருகிறது",
            "no_orders": "ஆர்டர்கள் எதுவும் இல்லை. உங்கள் முதல் பிரிண்ட்டைத் தொடங்குங்கள்!",
            "create_first_order": "முதல் ஆர்டரை உருவாக்கவும்",
            "unbeatable_pricing": "சிறந்த விலை",
            "secure_100": "100% பாதுகாப்பானது",
            "students_count": "1,200+ மாணவர்கள்",
            "get_started": "இப்போது தொடங்கவும்",
            "add_items": "அச்சிட உருப்படிகளைச் சேர்க்கவும்",
            "your_list": "உங்கள் ஆர்டர் பட்டியல்",
            "pdf_module": "PDF தொகுதி",
            "doc_module": "ஆவண தொகுதி",
            "upload_pdf_title": "PDF பதிவேற்றவும்",
            "browse_files": "உங்கள் கோப்புகளை உலாவ கிளிக் செய்யவும்",
            "preview": "முன்னோட்டம்",
            "edit_pages": "பக்கங்களைத் திருத்தவும்",
            "manual_format": "கைமுறை வடிவமைப்பு",
            "manual_format_desc": "வேர்ட் ஆவணங்களுக்கு சரியான அமைப்பை உறுதிப்படுத்த கைமுறை செயலாக்கம் தேவை. வாட்ஸ்அப் மூலம் சரிபார்க்கவும்.",
            "chat_whatsapp": "வாட்ஸ்அப்பில் அரட்டையடிக்கவும்",
            "special_instr": "சிறப்பு வழிமுறைகள்",
            "instr_placeholder": "எ.கா. சுருள் பிணைப்பு, லேமினேஷன், ஒற்றைப்படை பக்கங்களை மட்டும் அச்சிடவும்...",
            "advance_pay_label": "செலுத்த வேண்டிய முற்பணம் (50%)",
            "submit_pay": "சமர்ப்பித்து பணம் செலுத்தவும்",
            "premium_services": "பிரீமியம் சேவைகள்",
            "word_docs": "வேர்ட் ஆவணங்கள்",
            "word_coming_soon": "பதிவேற்றம், திருத்தம் மற்றும் மாற்றி அம்சங்கள்",
            "live_pdf_editor": "நேரடி PDF திருத்தி",
            "live_editor_desc": "வெளிப்புற கருவிகள் தேவையில்லை. தேவையற்ற பக்கங்களை அகற்றவும், நோக்குநிலையை சுழற்றவும், மேலும் எங்கள் தாவலிலேயே உங்கள் ஆவணத்தை முடிக்கவும்.",
            "digital_deliver": "டிஜிட்டல் விநியோகம்",
            "digital_desc": "உங்கள் இயற்பியல் அச்சுப்பொறிகளுடன் டிஜிட்டல் நகல்களைப் பெறுங்கள். எளிதாக மறு ஆர்டர் செய்ய உங்கள் முக்கியமான ஆவணங்களை நாங்கள் பாதுகாப்பாக சேமிக்கிறோம்.",
            "quality_quote": "\"தரம் வேகத்தை சந்திக்கும் இடம்\"",
            "new_feature": "புதிய அம்சம்",
            "contact_support": "தொடர்பு & ஆதரவு",
            "need_help_desc": "ஆர்டரில் உதவி தேவையா? கைமுறை ஆவண வடிவமைப்பு வேண்டுமா? வாட்ஸ்அப்பில் நேரடியாக எங்களுடன் அரட்டையடிக்கவும்.",
            "support_hours": "ஆதரவு நேரம்",
            "trust_secure": "100% பாதுகாப்பானது",
            "trust_secure_desc": "மறைகுறியாக்கப்பட்ட கொடுப்பனவுகள் & தரவு தனியுரிமை",
            "trust_fast": "மின்னல் வேகம்",
            "trust_fast_desc": "24 மணிநேர விநியோக உத்தரவாதம்",
            "trust_quality": "சிறந்த தரம்",
            "trust_quality_desc": "பிரீமியம் காகிதம் & தெளிவான பிரிண்டுகள்",
            "spending_analysis": "செலவு பகுப்பாய்வு",
            "last_7_days": "கடந்த 7 நாட்கள்",
            "daily_quote": "தினசரி உத்வேகம்",
            "design_quote": "வடிவமைப்பு என்பது அது எப்படி இருக்கிறது என்பது மட்டுமல்ல. வடிவமைப்பு என்பது அது எவ்வாறு செயல்படுகிறது என்பதே.",
            "lic_footer": "ஸ்மார்ட் ஜெராக்ஸ் & கோ. உரிமம் பெற்றது \u00A9 2024",
            "made_with_love": "மாணவர்களுக்காக \u2764\uFE0F உடன் உருவாக்கப்பட்டது",
            "morning_express": "மார்னிங் எக்ஸ்பிரஸ்",
            "morning_desc": "காலை 8 மணிக்கு முன் ஆர்டர் செய்யுங்கள், 10:30 க்கு பெறுங்கள்.",
            "live_pdf_desc": "பக்கங்களை உடனடியாகத் திருத்தவும், சுழற்றவும்.",
            "glass_binding": "கண்ணாடி தாள் பிணைப்பு",
            "glass_desc": "பிரீமியரம் பிணைப்பு இப்போது கிடைக்கிறது.",
            "conditions_apply": "நிபந்தனைகளுக்கு உட்பட்டது",
            "track_latest": "நேரடி நிலை: சமீபத்திய ஆர்டர்",
            "quote_1": "தொழில்நுட்பம் மக்களை ஒன்றிணைக்கும் போது சிறந்தது.",
            "quote_author_1": "மேட் முலன்வெக்",
            "quote_2": "இது பிழை அல்ல, இது அம்சம்.",
            "quote_author_2": "தெரியவில்லை",
            "quote_3": "பேச்சு மலிவானது. குறியீட்டைக் காட்டுங்கள்.",
            "quote_author_3": "லினஸ் டோர்வால்ட்ஸ்",
            "quote_4": "எளிமை செயல்திறனின் ஆன்மா.",
            "quote_author_4": "ஆஸ்டின் ஃப்ரீமேன்",
            "quote_5": "பசியோடு இருங்கள், முட்டாளாக இருங்கள்.",
            "quote_author_5": "ஸ்டீவ் ஜாப்ஸ்"
        }
    },
    gu: {
        translation: {
            "welcome": "સ્વાગત છે",
            "login_title": "પાછા સ્વાગત છે",
            "signup_title": "ખાતું બનાવો",
            "subtitle_login": "પ્રિન્ટિંગ ચાલુ રાખવા માટે સાઇન ઇન કરો",
            "subtitle_signup": "સ્માર્ટ પ્રિન્ટિંગ માટે અમારી સાથે જોડાઓ",
            "mobile": "મોબાઇલ નંબર",
            "login": "લૉગિન",
            "signup": "સાઇન અપ",
            "brand_name": "સ્માર્ટ ઝેરોક્ષ",
            "nav_dashboard": "ડેશબોર્ડ",
            "nav_login": "લૉગિન",
            "nav_signup": "સાઇન અપ",
            "nav_logout": "લૉગ આઉટ",
            "nav_profile": "પ્રોફાઇલ",
            "create_account": "ખાતું બનાવો",
            "welcome_back": "પાછા સ્વાગત છે",
            "signup_subtitle": "સ્માર્ટ પ્રિન્ટિંગ નેટવર્કમાં જોડાઓ",
            "login_subtitle": "તમારો અનુભવ ચાલુ રાખો",
            "confirm_pass": "પાસવર્ડની પુષ્ટિ કરો",
            "login_btn": "સાઇન ઇન",
            "already_account": "પહેલેથી જ એક ખાતું છે?",
            "no_account": "ખાતું નથી?",
            "dashboard": "ડેશબોર્ડ",
            "logout": "લૉગ આઉટ",
            "overview": "ઝાંખી",
            "services": "સેવાઓ",
            "support": "આધાર",
            "profile": "પ્રોફાઇલ",
            "total_orders": "કુલ ઓર્ડર",
            "total_spent": "કુલ ખર્ચ",
            "saved": "બચત",
            "trusted_users": "વિશ્વસનીય વપરાશકર્તાઓ",
            "recent_orders": "તાજેતરના ઓર્ડર",
            "our_services": "અમારી સેવાઓ અને કિંમત",
            "service_type": "સેવા પ્રકાર",
            "single_side": "એક બાજુ",
            "double_side": "બંને બાજુ",
            "bw_xerox": "ઝેરોક્ષ (બ્લેક એન્ડ વ્હાઇટ)",
            "bw_print": "પ્રિન્ટઆઉટ (બ્લેક એન્ડ વ્હાઇટ)",
            "color_print": "કલર પ્રિન્ટ",
            "spiral": "સ્પ સર્પાકાર બંધન",
            "glass_binding": "ગ્લાસ શીટ બાઈન્ડીંગ",
            "launching_soon": "ટૂંક સમયમાં આવી રહ્યું છે",
            "no_orders": "કોઈ ઓર્ડર મળ્યા નથી. તમારી પ્રથમ પ્રિન્ટ શરૂ કરો!",
            "create_first_order": "પ્રથમ ઓર્ડર બનાવો",
            "unbeatable_pricing": "અજેય ભાવ",
            "secure_100": "100% સુરક્ષિત",
            "students_count": "1,200+ વિદ્યાર્થીઓ",
            "get_started": "હવે શરૂ કરો",
            "add_items": "પ્રિન્ટ કરવા માટે આઈટમ્સ ઉમેરો",
            "your_list": "તમારી ઓર્ડર સૂચિ",
            "pdf_module": "પીડીએફ મોડ્યુલ",
            "doc_module": "દસ્તાવેજ મોડ્યુલ",
            "upload_pdf_title": "પીડીએફ અપલોડ કરો",
            "browse_files": "તમારી ફાઇલો બ્રાઉઝ કરવા માટે ક્લિક કરો",
            "preview": "પૂર્વાવલોકન",
            "edit_pages": "પૃષ્ઠો સંપાદિત કરો",
            "manual_format": "મેન્યુઅલ ફોર્મેટિંગ",
            "manual_format_desc": "વર્ડ દસ્તાવેજોને યોગ્ય લેઆઉટ સુનિશ્ચિત કરવા માટે મેન્યુઅલ પ્રોસેસિંગની જરૂર છે. કૃપા કરીને વોટ્સએપ દ્વારા ચકાસો.",
            "chat_whatsapp": "વોટ્સએપ પર ચેટ કરો",
            "special_instr": "વિશેષ સૂચનાઓ",
            "instr_placeholder": "દા.ત. સર્પાકાર બાઈન્ડીંગ, લેમિનેશન, ફક્ત એકી પૃષ્ઠો પ્રિન્ટ કરો...",
            "advance_pay_label": "ચૂકવવા માટે એડવાન્સ (50%)",
            "submit_pay": "સબમિટ કરો અને ચૂકવણી કરો",
            "premium_services": "પ્રીમિયમ સેવાઓ",
            "word_docs": "વર્ડ દસ્તાવેજો",
            "word_coming_soon": "અપલોડ, સંપાદન અને કન્વર્ટર સુવિધાઓ",
            "live_pdf_editor": "લાઇવ પીડીએફ એડિટર",
            "live_editor_desc": "બાહ્ય સાધનોની કોઈ જરૂર નથી. અનિચ્છનીય પૃષ્ઠો દૂર કરો, ઓરિએન્ટેશન ફેરવો અને અમારા ટૅબમાં જ તમારા દસ્તાવેજને આખરી ઓપ આપો.",
            "digital_deliver": "ડિજિટલ ડિલિવરી",
            "digital_desc": "તમારી ભૌતિક પ્રિન્ટ્સ સાથે ડિજિટલ નકલો મેળવો. અમે સરળ ફરીથી ઓર્ડર કરવા માટે તમારા મહત્વપૂર્ણ દસ્તાવેજોને સુરક્ષિત રીતે સંગ્રહિત કરીએ છીએ.",
            "quality_quote": "\"જ્યાં ગુણવત્તા ગતિ સાથે મળે છે\"",
            "new_feature": "નવી સુવિધા",
            "contact_support": "સંપર્ક અને આધાર",
            "need_help_desc": "ઓર્ડર સાથે મદદની જરૂર છે? મેન્યુઅલ દસ્તાવેજ ફોર્મેટિંગ જોઈએ છે? વોટ્સએપ પર સીધી અમારી સાથે ચેટ કરો.",
            "support_hours": "આધાર સમય",
            "trust_secure": "100% સુરક્ષિત",
            "trust_secure_desc": "એન્ક્રિપ્ટેડ પેમેન્ટ્સ અને ડેટા પ્રાઈવસી",
            "trust_fast": "વીજળીની ઝડપ",
            "trust_fast_desc": "24 કલાક ડિલિવરી ગેરંટી",
            "trust_quality": "શ્રેષ્ઠ ગુણવત્તા",
            "trust_quality_desc": "પ્રીમિયમ પેપર અને સ્પષ્ટ પ્રિન્ટ્સ",
            "spending_analysis": "ખર્ચ વિશ્લેષણ",
            "last_7_days": "છેલ્લા 7 દિવસ",
            "daily_quote": "દૈનિક પ્રેરણા",
            "design_quote": "ડિઝાઇન ફક્ત તે કેવું દેખાય છે અને લાગે છે તે નથી. ડિઝાઇન એ છે કે તે કેવી રીતે કાર્ય કરે છે.",
            "lic_footer": "સ્માર્ટ ઝેરોક્ષ એન્ડ કંપની દ્વારા લાઇસન્સ પ્રાપ્ત \u00A9 2024",
            "made_with_love": "વિદ્યાર્થીઓ માટે \u2764\uFE0F સાથે બનાવેલ",
            "morning_express": "મોર્નિંગ એક્સપ્રેસ",
            "morning_desc": "સવારે 8 પહેલા ઓર્ડર કરો, 10:30 સુધી મેળવો.",
            "live_pdf_desc": "પૃષ્ઠોને તરત જ સંપાદિત કરો, ફેરવો.",
            "glass_binding": "ગ્લાસ શીટ બાઈન્ડીંગ",
            "glass_desc": "પ્રીમિયમ બાઈન્ડીંગ હવે ઉપલબ્ધ છે.",
            "conditions_apply": "શરતો લાગુ",
            "track_latest": "લાઇવ સ્ટેટસ: નવીનતમ ઓર્ડર",
            "quote_1": "ટેક્નોલોજી શ્રેષ્ઠ છે જ્યારે તે લોકોને એક સાથે લાવે છે.",
            "quote_author_1": "મેટ મુલેનવેગ",
            "quote_2": "આ બગ નથી, આ ફીચર છે.",
            "quote_author_2": "અજ્ઞાત",
            "quote_3": "વાતો સસ્તી છે. મને કોડ બતાવો.",
            "quote_author_3": "લિનસ ટોરવાલ્ડ્સ",
            "quote_4": "સરળતા કાર્યક્ષમતાનો આત્મા છે.",
            "quote_author_4": "ઓસ્ટિન ફ્રીમેન",
            "quote_5": "ભૂખ્યા રહો, મૂર્ખ રહો.",
            "quote_author_5": "સ્ટીવ જોબ્સ"
        }
    },
    ml: {
        translation: {
            "welcome": "സ്വാഗതം",
            "login_title": "വീണ്ടും സ്വാഗതം",
            "signup_title": "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
            "subtitle_login": "പ്രിന്റിംഗ് തുടരാൻ സൈൻ ഇൻ ചെയ്യുക",
            "subtitle_signup": "സ്മാർട്ട് പ്രിന്റിംഗിനായി ഞങ്ങളോടൊപ്പം ചേരൂ",
            "mobile": "മൊബൈൽ നമ്പർ",
            "login": "ലോഗിൻ",
            "signup": "സൈൻ അപ്പ്",
            "brand_name": "സ്മാർട്ട് സിറോക്സ്",
            "nav_dashboard": "ഡാഷ്‌ബോർഡ്",
            "nav_login": "ലോഗിൻ",
            "nav_signup": "സൈൻ അപ്പ്",
            "nav_logout": "ലോഗ് ഔട്ട്",
            "nav_profile": "പ്രൊഫൈൽ",
            "create_account": "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
            "welcome_back": "വീണ്ടും സ്വാഗതം",
            "signup_subtitle": "സ്മാർട്ട് പ്രിന്റിംഗ് നെറ്റ്‌വർക്കിൽ ചേരുക",
            "login_subtitle": "നിങ്ങളുടെ അനുഭവം തുടരുക",
            "confirm_pass": "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
            "login_btn": "സൈൻ ഇൻ",
            "already_account": "ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ?",
            "no_account": "അക്കൗണ്ട് ഇല്ലേ?",
            "dashboard": "ഡാഷ്‌ബോർഡ്",
            "logout": "ലോഗ് ഔട്ട്",
            "overview": "അവലോകനം",
            "services": "സേവനങ്ങൾ",
            "support": "പിന്തുണ",
            "profile": "പ്രൊഫൈൽ",
            "total_orders": "ആകെ ഓർഡറുകൾ",
            "total_spent": "ആകെ ചിലവ്",
            "saved": "സംരക്ഷിച്ചു",
            "trusted_users": "വിശ്വസ്തരായ ഉപയോക്താക്കൾ",
            "recent_orders": "സമീപകാല ഓർഡറുകൾ",
            "our_services": "ഞങ്ങളുടെ സേവനങ്ങളും വിലനിർണ്ണയവും",
            "service_type": "സേവന തരം",
            "single_side": "ഒരു വശം",
            "double_side": "രണ്ട് വശം",
            "bw_xerox": "സിറോക്സ് (B&W)",
            "bw_print": "പ്രിന്റൗട്ട് (B&W)",
            "color_print": "കളർ പ്രിന്റ്",
            "spiral": "സ്പൈറൽ ബൈൻഡിംഗ്",
            "glass_binding": "ഗ്ലാസ് ഷീറ്റ് ബൈൻഡിംഗ്",
            "launching_soon": "ഉടൻ വരുന്നു",
            "no_orders": "ഓർഡറുകളൊന്നും കണ്ടെത്തിയില്ല. നിങ്ങളുടെ ആദ്യ പ്രിന്റ് ആരംഭിക്കുക!",
            "create_first_order": "ആദ്യ ഓർഡർ സൃഷ്ടിക്കുക",
            "unbeatable_pricing": "മികച്ച വിലകൾ",
            "secure_100": "100% സുരക്ഷിതം",
            "students_count": "1,200+ വിദ്യാർത്ഥികൾ",
            "get_started": "ഇപ്പോൾ ആരംഭിക്കുക",
            "add_items": "പ്രിന്റ് ചെയ്യാൻ ഇനങ്ങൾ ചേർക്കുക",
            "your_list": "നിങ്ങളുടെ ഓർഡർ ലിസ്റ്റ്",
            "pdf_module": "PDF മൊഡ്യൂൾ",
            "doc_module": "ഡോക്യുമെന്റ് മൊഡ്യൂൾ",
            "upload_pdf_title": "PDF അപ്‌ലോഡ് ചെയ്യുക",
            "browse_files": "നിങ്ങളുടെ ഫയലുകൾ ബ്രൗസ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക",
            "preview": "പ്രിവ്യൂ",
            "edit_pages": "പേജുകൾ എഡിറ്റ് ചെയ്യുക",
            "manual_format": "മാനുവൽ ഫോർമാറ്റിംഗ്",
            "manual_format_desc": "വേർഡ് ഡോക്യുമെന്റുകൾക്ക് കൃത്യമായ ലേഔട്ട് ഉറപ്പാക്കാൻ മാനുവൽ പ്രോസസ്സിംഗ് ആവശ്യമാണ്. ദയവായി വാട്ട്‌സ്ആപ്പ് വഴി പരിശോധിക്കുക.",
            "chat_whatsapp": "വാട്ട്‌സ്ആപ്പിൽ ചാറ്റ് ചെയ്യുക",
            "special_instr": "പ്രത്യേക നിർദ്ദേശങ്ങൾ",
            "instr_placeholder": "ഉദാ. സ്പൈറൽ ബൈൻഡിംഗ്, ലാമിനേഷൻ, ഒറ്റ പേജുകൾ മാത്രം പ്രിന്റ് ചെയ്യുക...",
            "advance_pay_label": "അടയ്ക്കാനുള്ള അഡ്വാൻസ് (50%)",
            "submit_pay": "സമർപ്പിക്കുക & പണമടയ്ക്കുക",
            "premium_services": "പ്രീമിയം സേവനങ്ങൾ",
            "word_docs": "വേർഡ് ഡോക്യുമെന്റുകൾ",
            "word_coming_soon": "അപ്‌ലോഡ്, എഡിറ്റ് & കൺവെർട്ടർ ഫീച്ചറുകൾ",
            "live_pdf_editor": "ലൈവ് PDF എഡിറ്റർ",
            "live_editor_desc": "പുറത്തുള്ള ടൂളുകളുടെ ആവശ്യമില്ല. ആവശ്യമില്ലാത്ത പേജുകൾ നീക്കം ചെയ്യുക, ഓറിയന്റേഷൻ തിരിക്കുക, ഞങ്ങളുടെ ടാബിൽ തന്നെ നിങ്ങളുടെ ഡോക്യുമെന്റ് പൂർത്തിയാക്കുക.",
            "digital_deliver": "ഡിജിറ്റൽ ഡെലിവറി",
            "digital_desc": "നിങ്ങളുടെ ഫിസിക്കൽ പ്രിന്റുകൾക്കൊപ്പം ഡിജിറ്റൽ പകർപ്പുകളും നേടുക. എളുപ്പത്തിൽ വീണ്ടും ഓർഡർ ചെയ്യുന്നതിനായി ഞങ്ങൾ നിങ്ങളുടെ പ്രധാനപ്പെട്ട രേഖകൾ സുരക്ഷിതമായി സൂക്ഷിക്കുന്നു.",
            "quality_quote": "\"ഗുണനിലവാരം വേഗതയെ കണ്ടുമുട്ടുന്നിടത്ത്\"",
            "new_feature": "പുതിയ ഫീച്ചർ",
            "contact_support": "ബന്ധപ്പെടുക & പിന്തുണ",
            "need_help_desc": "ഓർഡറിൽ സഹായം ആവശ്യമുണ്ടോ? മാനുവൽ ഡോക്യുമെന്റ് ഫോർമാറ്റിംഗ് വേണോ? വാട്ട്‌സ്ആപ്പിൽ നേരിട്ട് ഞങ്ങളുമായി ചാറ്റ് ചെയ്യുക.",
            "support_hours": "പിന്തുണ സമയം",
            "trust_secure": "100% സുരക്ഷിതം",
            "trust_secure_desc": "എൻക്രിപ്റ്റ് ചെയ്ത പേയ്‌മെന്റുകളും ഡാറ്റ സ്വകാര്യതയും",
            "trust_fast": "മിന്നൽ വേഗത",
            "trust_fast_desc": "24 മണിക്കൂർ ഡെലിവറി ഗ്യാരണ്ടി",
            "trust_quality": "മികച്ച ഗുണനിലവാരം",
            "trust_quality_desc": "പ്രീമിയം പേപ്പറും വ്യക്തമായ പ്രിന്റുകളും",
            "spending_analysis": "ചെലവ് വിശകലനം",
            "last_7_days": "കഴിഞ്ഞ 7 ദിവസങ്ങൾ",
            "daily_quote": "ദൈനംദിന പ്രചോദനം",
            "design_quote": "ഡിസൈൻ എന്നത് അത് എങ്ങനെയുണ്ടെന്നോ അനുഭവപ്പെടുന്നെന്നോ മാത്രമല്ല. അതെങ്ങനെ പ്രവർത്തിക്കുന്നു എന്നതാണ് ഡിസൈൻ.",
            "lic_footer": "സ്മാർട്ട് സിറോക്സ് & കോ ലൈസൻസ് ചെയ്തത് \u00A9 2024",
            "made_with_love": "വിദ്യാർത്ഥികൾക്കായി \u2764\uFE0F ഉപയോഗിച്ച് നിർമ്മിച്ചത്",
            "morning_express": "മോണിംഗ് എക്സ്പ്രസ്",
            "morning_desc": "രാവിലെ 8 ന് മുമ്പ് ഓർഡർ ചെയ്യുക, 10:30 ന് നേടുക.",
            "live_pdf_desc": "പേജുകൾ തൽക്ഷണം എഡിറ്റുചെയ്യുക, തിരിക്കുക.",
            "glass_binding": "ഗ്വാസ് ഷീറ്റ് ബൈൻഡിംഗ്",
            "glass_desc": "പ്രീമിയം ബൈൻഡിംഗ് ഇപ്പോൾ ലഭ്യമാണ്.",
            "conditions_apply": "നിബന്ധനകൾ ബാധകം",
            "track_latest": "തത്സമയ നില: ഏറ്റവും പുതിയ ഓർഡർ",
            "quote_1": "സാങ്കേതികവിദ്യ ആളുകളെ ഒരുമിച്ച് കൊണ്ടുവരുമ്പോൾ മികച്ചതാണ്.",
            "quote_author_1": "മാറ്റ് മുള്ളൻവെഗ്",
            "quote_2": "ഇതൊരു ബഗ് അല്ല, ഇതൊരു ഫീച്ചറാണ്.",
            "quote_author_2": "അജ്ഞാതം",
            "quote_3": "സംസാരം എളുപ്പമാണ്. കോഡ് കാണിക്കൂ.",
            "quote_author_3": "ലിനസ് ടോർവാൾഡ്സ്",
            "quote_4": "ലളിതത കാര്യക്ഷമതയുടെ ആത്മാവാണ്.",
            "quote_author_4": "ഓസ്റ്റിൻ ഫ്രീമാൻ",
            "quote_5": "വിശപ്പുള്ളവരായിരിക്കുക, വിഡ്ഢികളായിരിക്കുക.",
            "quote_author_5": "സ്റ്റീവ് ജോബ്സ്"
        }
    },
    or: {
        translation: {
            "welcome": "ସ୍ୱାଗତ",
            "login_title": "ପୁନର୍ବାର ସ୍ୱାଗତ",
            "signup_title": "ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ",
            "subtitle_login": "ପ୍ରିଣ୍ଟିଙ୍ଗ୍ ଜାରି ରଖିବାକୁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ",
            "subtitle_signup": "ସ୍ମାର୍ଟ ପ୍ରିଣ୍ଟିଙ୍ଗ୍ ପାଇଁ ଆମ ସହିତ ଯୋଗ ଦିଅନ୍ତୁ",
            "mobile": "ମୋବାଇଲ୍ ନମ୍ବର",
            "login": "ଲଗ୍ ଇନ୍",
            "signup": "ସାଇନ୍ ଅପ୍",
            "brand_name": "ସ୍ମାର୍ଟ ଜେରକ୍ସ",
            "nav_dashboard": "ଡ୍ୟାସବୋର୍ଡ",
            "nav_login": "ଲଗ୍ ଇନ୍",
            "nav_signup": "ସାଇନ୍ ଅପ୍",
            "nav_logout": "ଲଗ୍ ଆଉଟ୍",
            "nav_profile": "ପ୍ରୋଫାଇଲ୍",
            "create_account": "ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ",
            "welcome_back": "ପୁନର୍ବାର ସ୍ୱାଗତ",
            "signup_subtitle": "ସ୍ମାର୍ଟ ପ୍ରିଣ୍ଟିଙ୍ଗ୍ ନେଟୱାର୍କରେ ଯୋଗ ଦିଅନ୍ତୁ",
            "login_subtitle": "ଆପଣଙ୍କ ଅନୁଭବ ଜାରି ରଖନ୍ତୁ",
            "confirm_pass": "ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ",
            "login_btn": "ସାଇନ୍ ଇନ୍",
            "already_account": "ପୂର୍ବରୁ ଆକାଉଣ୍ଟ୍ ଅଛି କି?",
            "no_account": "ଆକାଉଣ୍ଟ୍ ନାହିଁ କି?",
            "dashboard": "ଡ୍ୟାସବୋର୍ଡ",
            "logout": "ଲଗ୍ ଆଉଟ୍",
            "overview": "ସମୀକ୍ଷା",
            "services": "ସେବା",
            "support": "ସହାୟତା",
            "profile": "ପ୍ରୋଫାଇଲ୍",
            "total_orders": "ସମୁଦାୟ ଅର୍ଡର",
            "total_spent": "ସମୁଦାୟ ଖର୍ଚ୍ଚ",
            "saved": "ସଞ୍ଚୟ",
            "trusted_users": "ବିଶ୍ୱସ୍ତ ବ୍ୟବହାରକାରୀ",
            "recent_orders": "ସାମ୍ପ୍ରତିକ ଅର୍ଡର",
            "our_services": "ଆମର ସେବା ଏବଂ ମୂଲ୍ୟ",
            "service_type": "ସେବା ପ୍ରକାର",
            "single_side": "ଗୋଟିଏ ପାର୍ଶ୍ୱ",
            "double_side": "ଉଭୟ ପାର୍ଶ୍ୱ",
            "bw_xerox": "ଜେରକ୍ସ (B&W)",
            "bw_print": "ପ୍ରିଣ୍ଟଆଉଟ୍ (B&W)",
            "color_print": "ରଙ୍ଗୀନ୍ ପ୍ରିଣ୍ଟ୍",
            "spiral": "ସ୍ପାଇରାଲ୍ ବାଇଣ୍ଡିଂ",
            "glass_binding": "ଗ୍ଲାସ୍ ସିଟ୍ ବାଇଣ୍ଡିଂ",
            "launching_soon": "ଶୀଘ୍ର ଆସୁଛି",
            "no_orders": "କୌଣସି ଅର୍ଡର ମିଳିଲା ନାହିଁ | ଆପଣଙ୍କର ପ୍ରଥମ ପ୍ରିଣ୍ଟ୍ ଆରମ୍ଭ କରନ୍ତୁ!",
            "create_first_order": "ପ୍ରଥମ ଅର୍ଡର କରନ୍ତୁ",
            "unbeatable_pricing": "ଅତୁଳନୀୟ ମୂଲ୍ୟ",
            "secure_100": "100% ସୁରକ୍ଷିତ",
            "students_count": "1,200+ ଛାତ୍ର",
            "get_started": "ବର୍ତ୍ତମାନ ଆରମ୍ଭ କରନ୍ତୁ",
            "add_items": "ପ୍ରିଣ୍ଟ୍ କରିବାକୁ ଆଇଟମ୍ ଯୋଡନ୍ତୁ",
            "your_list": "ଆପଣଙ୍କର ଅର୍ଡର ତାଲିକା",
            "pdf_module": "PDF ମଡ୍ୟୁଲ୍",
            "doc_module": "ଡକ୍ୟୁମେଣ୍ଟ୍ ମଡ୍ୟୁଲ୍",
            "upload_pdf_title": "PDF ଅପଲୋଡ୍ କରନ୍ତୁ",
            "browse_files": "ଆପଣଙ୍କର ଫାଇଲ୍ ବ୍ରାଉଜ୍ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ",
            "preview": "ପୂର୍ବାବଲୋକନ",
            "edit_pages": "ପୃଷ୍ଠା ଏଡିଟ୍ କରନ୍ତୁ",
            "manual_format": "ମାନୁଆଲ୍ ଫର୍ମାଟିଂ",
            "manual_format_desc": "ୱାର୍ଡ ଡକ୍ୟୁମେଣ୍ଟଗୁଡିକ ସଠିକ୍ ଲେଆଉଟ୍ ନିଶ୍ଚିତ କରିବାକୁ ମାନୁଆଲ୍ ପ୍ରୋସେସିଂ ଆବଶ୍ୟକ କରେ | ଦୟାକରି ହ୍ୱାଟସ୍ ଆପ୍ ମାଧ୍ୟମରେ ଯାଞ୍ଚ କରନ୍ତୁ |",
            "chat_whatsapp": "ହ୍ୱାଟସ୍ ଆପ୍ ରେ ଚାଟ୍ କରନ୍ତୁ",
            "special_instr": "ବିଶେଷ ନିର୍ଦ୍ଦେଶାବଳୀ",
            "instr_placeholder": "ଯେପରିକି ସ୍ପାଇରାଲ୍ ବାଇଣ୍ଡିଂ, ଲାମିନେସନ୍, କେବଳ ବିଷମ ପୃଷ୍ଠା ପ୍ରିଣ୍ଟ୍ କରନ୍ତୁ...",
            "advance_pay_label": "ଦେବାକୁ ଥିବା ଅଗ୍ରିମ (50%)",
            "submit_pay": "ଦାଖଲ କରନ୍ତୁ ଏବଂ ଦେୟ ଦିଅନ୍ତୁ",
            "premium_services": "ପ୍ରିମିୟମ୍ ସେବା",
            "word_docs": "ୱାର୍ଡ ଡକ୍ୟୁମେଣ୍ଟ୍",
            "word_coming_soon": "ଅପଲୋଡ୍, ଏଡିଟ୍ ଏବଂ କନଭର୍ଟର ଫିଚର",
            "live_pdf_editor": "ଲାଇଭ୍ PDF ଏଡିଟର୍",
            "live_editor_desc": "ବାହ୍ୟ ଉପକରଣର କୌଣସି ଆବଶ୍ୟକତା ନାହିଁ | ଅଦରକାରୀ ପୃଷ୍ଠାଗୁଡ଼ିକୁ ହଟାନ୍ତୁ, ଓରିଏଣ୍ଟେସନ୍ ଘୂରାନ୍ତୁ, ଏବଂ ଆମର ଟ୍ୟାବ୍ ରେ ଆପଣଙ୍କର ଡକ୍ୟୁମେଣ୍ଟ୍ କୁ ଚୂଡ଼ାନ୍ତ କରନ୍ତୁ |",
            "digital_deliver": "ଡିଜିଟାଲ୍ ଡେଲିଭରୀ",
            "digital_desc": "ଆପଣଙ୍କର ଭୌତିକ ପ୍ରିଣ୍ଟ୍ ସହିତ ଡିଜିଟାଲ୍ କପି ପାଆନ୍ତୁ | ସହଜ ରି-ଅର୍ଡର ପାଇଁ ଆମେ ଆପଣଙ୍କର ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଡକ୍ୟୁମେଣ୍ଟ୍ କୁ ସୁରକ୍ଷିତ ରଖୁ |",
            "quality_quote": "\"ଯେଉଁଠାରେ ଗୁଣବତ୍ତା ଗତି ସହିତ ମିଳେ\"",
            "new_feature": "ନୂତନ ଫିଚର",
            "contact_support": "ଯୋଗାଯୋଗ ଏବଂ ସହାୟତା",
            "need_help_desc": "ଅର୍ଡର ସହିତ ସାହାଯ୍ୟ ଆବଶ୍ୟକ କି? ମାନୁଆଲ୍ ଡକ୍ୟୁମେଣ୍ଟ୍ ଫର୍ମାଟିଂ ଚାହୁଁଛନ୍ତି କି? ହ୍ୱାଟସ୍ ଆପ୍ ରେ ସିଧାସଳଖ ଆମ ସହିତ ଚାଟ୍ କରନ୍ତୁ |",
            "support_hours": "ସହାୟତା ସମୟ",
            "trust_secure": "100% ସୁରକ୍ଷିତ",
            "trust_secure_desc": "ଏନକ୍ରିପ୍ଟେଡ୍ ପେମେଣ୍ଟ୍ ଏବଂ ଡାଟା ଗୋପନୀୟତା",
            "trust_fast": "ବିଜୁଳି ବେଗ",
            "trust_fast_desc": "24 ଘଣ୍ଟା ଡେଲିଭରୀ ଗ୍ୟାରେଣ୍ଟି",
            "trust_quality": "ସର୍ବୋତ୍ତମ ଗୁଣବତ୍ତା",
            "trust_quality_desc": "ପ୍ରିମିୟମ୍ କାଗଜ ଏବଂ ସ୍ପଷ୍ଟ ପ୍ରିଣ୍ଟ୍",
            "spending_analysis": "ଖର୍ଚ୍ଚ ବିଶ୍ଳେଷଣ",
            "last_7_days": "ଗତ 7 ଦିନ",
            "daily_quote": "ଦୈନିକ ପ୍ରେରଣା",
            "design_quote": "ଡିଜାଇନ୍ କେବଳ ଦେଖିବାକୁ କିମ୍ବା ଅନୁଭବ କରିବାକୁ ନୁହେଁ | ଡିଜାଇନ୍ ହେଉଛି ଏହା କିପରି କାମ କରେ |",
            "lic_footer": "ସ୍ମାର୍ଟ ଜେରକ୍ସ ଆଣ୍ଡ କୋ ଦ୍ୱାରା ଲାଇସେନ୍ସପ୍ରାପ୍ତ \u00A9 2024",
            "made_with_love": "ଛାତ୍ରମାନଙ୍କ ପାଇଁ \u2764\uFE0F ସହିତ ତିଆରି",
            "morning_express": "ମର୍ଣ୍ଣିଂ ଏକ୍ସପ୍ରେସ୍",
            "morning_desc": "ସକାଳ 8 ପୂର୍ବରୁ ଅର୍ଡର କରନ୍ତୁ, 10:30 ରେ ପାଆନ୍ତୁ |",
            "live_pdf_desc": "ତୁରନ୍ତ ପୃଷ୍ଠା ଏଡିଟ୍ କରନ୍ତୁ, ଘୁରାନ୍ତୁ |",
            "glass_binding": "ଗ୍ଲାସ୍ ସିଟ୍ ବାଇଣ୍ଡିଂ",
            "glass_desc": "ପ୍ରିମିୟମ୍ ବାଇଣ୍ଡିଂ ବର୍ତ୍ତମାନ ଉପଲବ୍ଧ |",
            "conditions_apply": "ସର୍ତ୍ତାବଳୀ ପ୍ରଯୁଜ୍ୟ",
            "track_latest": "ଲାଇଭ୍ ସ୍ଥିତି: ଅର୍ଡର",
            "quote_1": "ଟେକ୍ନୋଲୋଜି ସର୍ବୋତ୍ତମ ଅଟେ ଯେତେବେଳେ ଏହା ଲୋକଙ୍କୁ ଏକାଠି କରେ |",
            "quote_author_1": "ମ୍ୟାଟ୍ ମୁଲେନୱେଗ୍",
            "quote_2": "ଏହା ଏକ ବଗ୍ ନୁହେଁ, ଏହା ଏକ ପିଚର୍ |",
            "quote_author_2": "ଅଜ୍ଞାତ",
            "quote_3": "କଥା ଶସ୍ତା ଅଟେ | ମୋତେ କୋଡ୍ ଦେଖାନ୍ତୁ |",
            "quote_author_3": "ଲିନସ୍ ଟୋରଭାଲ୍ଡସ୍",
            "quote_4": "ସରଳତା ଦକ୍ଷତାର ଆତ୍ମା ​​ଅଟେ |",
            "quote_author_4": "ଅଷ୍ଟିନ ଫ୍ରିମ୍ୟାନ୍",
            "quote_5": "ଭୋକିଲା ରୁହନ୍ତୁ, ବୋକା ରୁହନ୍ତୁ |",
            "quote_author_5": "ଷ୍ଟିଭ୍ ଜବ୍ସ"
        }
    },
    pa: {
        translation: {
            "welcome": "ਜੀ ਆਇਆਂ ਨੂੰ",
            "login_title": "ਵਾਪਸੀ ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ",
            "signup_title": "ਖਾਤਾ ਬਣਾਓ",
            "subtitle_login": "ਪ੍ਰਿੰਟਿੰਗ ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ",
            "subtitle_signup": "ਸਮਾਰਟ ਪ੍ਰਿੰਟਿੰਗ ਲਈ ਸਾਡੇ ਨਾਲ ਜੁੜੋ",
            "mobile": "ਮੋਬਾਈਲ ਨੰਬਰ",
            "login": "ਲੌਗ ਇਨ",
            "signup": "ਸਾਈਨ ਅੱਪ",
            "brand_name": "ਸਮਾਰਟ ਜ਼ਿਰਾਕਸ",
            "nav_dashboard": "ਡੈਸ਼ਬੋਰਡ",
            "nav_login": "ਲੌਗ ਇਨ",
            "nav_signup": "ਸਾਈਨ ਅੱਪ",
            "nav_logout": "ਲੌਗ ਆਉਟ",
            "nav_profile": "ਪ੍ਰੋਫਾਈਲ",
            "create_account": "ਖਾਤਾ ਬਣਾਓ",
            "welcome_back": "ਵਾਪਸੀ ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ",
            "signup_subtitle": "ਵਧੀਆ ਪ੍ਰਿੰਟਿੰਗ ਨੈੱਟਵਰਕ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ",
            "login_subtitle": "ਆਪਣਾ ਅਨੁਭਵ ਜਾਰੀ ਰੱਖੋ",
            "confirm_pass": "ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
            "login_btn": "ਸਾਈਨ ਇਨ",
            "already_account": "ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?",
            "no_account": "ਕੀ ਖਾਤਾ ਨਹੀਂ ਹੈ?",
            "dashboard": "ਡੈਸ਼ਬੋਰਡ",
            "logout": "ਲੌਗ ਆਉਟ",
            "overview": "ਸੰਖੇਪ ਜਾਣਕਾਰੀ",
            "services": "ਸੇਵਾਵਾਂ",
            "support": "ਸਹਾਇਤਾ",
            "profile": "ਪ੍ਰੋਫਾਈਲ",
            "total_orders": "ਕੁੱਲ ਆਰਡਰ",
            "total_spent": "ਕੁੱਲ ਖਰਚ",
            "saved": "ਬਚਤ",
            "trusted_users": "ਭਰੋਸੇਯੋਗ ਉਪਭੋਗਤਾ",
            "recent_orders": "ਹਾਲੀਆ ਆਰਡਰ",
            "our_services": "ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ ਅਤੇ ਕੀਮਤਾਂ",
            "service_type": "ਸੇਵਾ ਦੀ ਕਿਸਮ",
            "single_side": "ਇੱਕ ਪਾਸੇ",
            "double_side": "ਦੋਵੇਂ ਪਾਸੇ",
            "bw_xerox": "ਜ਼ਿਰਾਕਸ (ਬਲੈਕ ਐਂਡ ਵ੍ਹਾਈਟ)",
            "bw_print": "ਪ੍ਰਿੰਟਆਉਟ (ਬਲੈਕ ਐਂਡ ਵ੍ਹਾਈਟ)",
            "color_print": "ਰੰਗਦਾਰ ਪ੍ਰਿੰਟ",
            "spiral": "ਸਪਾਈਰਲ ਬਾਈਂਡਿੰਗ",
            "glass_binding": "ਗਲਾਸ ਸ਼ੀਟ ਬਾਈਂਡਿੰਗ",
            "launching_soon": "ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ",
            "no_orders": "ਕੋਈ ਆਰਡਰ ਨਹੀਂ ਮਿਲਿਆ। ਆਪਣਾ ਪਹਿਲਾ ਪ੍ਰਿੰਟ ਸ਼ੁਰੂ ਕਰੋ!",
            "create_first_order": "ਪਹਿਲਾ ਆਰਡਰ ਬਣਾਓ",
            "unbeatable_pricing": "ਬੇਮਿਸਾਲ ਕੀਮਤਾਂ",
            "secure_100": "100% ਸੁਰੱਖਿਅਤ",
            "students_count": "1,200+ ਵਿਦਿਆਰਥੀ",
            "get_started": "ਹੁਣੇ ਸ਼ੁਰੂ ਕਰੋ",
            "add_items": "ਪ੍ਰਿੰਟ ਕਰਨ ਲਈ ਆਈਟਮਾਂ ਸ਼ਾਮਲ ਕਰੋ",
            "your_list": "ਤੁਹਾਡੀ ਆਰਡਰ ਸੂਚੀ",
            "pdf_module": "PDF ਮੋਡੀਊਲ",
            "doc_module": "ਦਸਤਾਵੇਜ਼ ਮੋਡੀਊਲ",
            "upload_pdf_title": "PDF ਅਪਲੋਡ ਕਰੋ",
            "browse_files": "ਆਪਣੀਆਂ ਫਾਈਲਾਂ ਬ੍ਰਾਊਜ਼ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ",
            "preview": "ਝਲਕ",
            "edit_pages": "ਸਫ਼ੇ ਸੰਪਾਦਿਤ ਕਰੋ",
            "manual_format": "ਮੈਨੁਅਲ ਫਾਰਮੈਟਿੰਗ",
            "manual_format_desc": "ਵਰਡ ਦਸਤਾਵੇਜ਼ਾਂ ਨੂੰ ਸਹੀ ਲੇਆਉਟ ਯਕੀਨੀ ਬਣਾਉਣ ਲਈ ਮੈਨੁਅਲ ਪ੍ਰੋਸੈਸਿੰਗ ਦੀ ਲੋੜ ਹੁੰਦੀ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ WhatsApp ਰਾਹੀਂ ਪੁਸ਼ਟੀ ਕਰੋ।",
            "chat_whatsapp": "WhatsApp 'ਤੇ ਗੱਲਬਾਤ ਕਰੋ",
            "special_instr": "ਖਾਸ ਹਦਾਇਤਾਂ",
            "instr_placeholder": "ਉਦਾ. ਸਪਿਰਲ ਬਾਈਂਡਿੰਗ, ਲੈਮੀਨੇਸ਼ਨ, ਸਿਰਫ਼ ਔਡ ਸਫ਼ੇ ਪ੍ਰਿੰਟ ਕਰੋ...",
            "advance_pay_label": "ਭੁਗਤਾਨ ਕਰਨ ਲਈ ਅਡਵਾਂਸ (50%)",
            "submit_pay": "ਜਮ੍ਹਾਂ ਕਰੋ ਅਤੇ ਭੁਗਤਾਨ ਕਰੋ",
            "premium_services": "ਪ੍ਰੀਮੀਅਮ ਸੇਵਾਵਾਂ",
            "word_docs": "ਵਰਡ ਦਸਤਾਵੇਜ਼",
            "word_coming_soon": "ਅਪਲੋਡ, ਸੰਪਾਦਨ ਅਤੇ ਕਨਵਰਟਰ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
            "live_pdf_editor": "ਲਾਈਵ PDF ਸੰਪਾਦਕ",
            "live_editor_desc": "ਬਾਹਰੀ ਟੂਲਸ ਦੀ ਕੋਈ ਲੋੜ ਨਹੀਂ। ਅਣਚਾਹੇ ਸਫ਼ੇ ਹਟਾਓ, ਸਥਿਤੀ ਘੁੰਮਾਓ, ਅਤੇ ਆਪਣੇ ਦਸਤਾਵੇਜ਼ ਨੂੰ ਇੱਥੇ ਸਾਡੇ ਟੈਬ ਵਿੱਚ ਅੰਤਿਮ ਰੂਪ ਦਿਓ।",
            "digital_deliver": "ਡਿਜੀਟਲ ਡਿਲਿਵਰੀ",
            "digital_desc": "ਆਪਣੇ ਭੌਤਿਕ ਪ੍ਰਿੰਟਸ ਦੇ ਨਾਲ ਡਿਜੀਟਲ ਕਾਪੀਆਂ ਪ੍ਰਾਪਤ ਕਰੋ। ਅਸੀਂ ਆਸਾਨ ਰੀ-ਆਰਡਰ ਲਈ ਤੁਹਾਡੇ ਮਹੱਤਵਪੂਰਨ ਦਸਤਾਵੇਜ਼ਾਂ ਨੂੰ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਸਟੋਰ ਕਰਦੇ ਹਾਂ।",
            "quality_quote": "\"ਜਿੱਥੇ ਗੁਣਵੱਤਾ ਗਤੀ ਨੂੰ ਮਿਲਦੀ ਹੈ\"",
            "new_feature": "ਨਵੀਂ ਵਿਸ਼ੇਸ਼ਤਾ",
            "contact_support": "ਸੰਪਰਕ ਅਤੇ ਸਹਾਇਤਾ",
            "need_help_desc": "ਆਰਡਰ ਲਈ ਮਦਦ ਚਾਹੀਦੀ ਹੈ? ਮੈਨੁਅਲ ਦਸਤਾਵੇਜ਼ ਫਾਰਮੈਟਿੰਗ ਚਾਹੁੰਦੇ ਹੋ? WhatsApp 'ਤੇ ਸਾਡੇ ਨਾਲ ਸਿੱਧੀ ਗੱਲਬਾਤ ਕਰੋ।",
            "support_hours": "ਸਹਾਇਤਾ ਸਮਾਂ",
            "trust_secure": "100% ਸੁਰੱਖਿਅਤ",
            "trust_secure_desc": "ਇਨਕ੍ਰਿਪਟਡ ਭੁਗਤਾਨ ਅਤੇ ਡਾਟਾ ਗੋਪਨੀਯਤਾ",
            "trust_fast": "ਬਿਜਲੀ ਦੀ ਗਤੀ",
            "trust_fast_desc": "24 ਘੰਟੇ ਡਿਲਿਵਰੀ ਗਰੰਟੀ",
            "trust_quality": "ਵਧੀਆ ਗੁਣਵੱਤਾ",
            "trust_quality_desc": "ਪ੍ਰੀਮੀਅਮ ਪੇਪਰ ਅਤੇ ਸਾਫ਼ ਪ੍ਰਿੰਟ",
            "spending_analysis": "ਖਰਚ ਵਿਸ਼ਲੇਸ਼ਣ",
            "last_7_days": "ਪਿਛਲੇ 7 ਦਿਨ",
            "daily_quote": "ਰੋਜ਼ਾਨਾ ਪ੍ਰੇਰਣਾ",
            "design_quote": "ਡਿਜ਼ਾਈਨ ਸਿਰਫ਼ ਉਹ ਨਹੀਂ ਜੋ ਦਿਖਦਾ ਹੈ ਅਤੇ ਮਹਿਸੂਸ ਹੁੰਦਾ ਹੈ। ਡਿਜ਼ਾਈਨ ਉਹ ਹੈ ਕਿ ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ।",
            "lic_footer": "ਸਮਾਰਟ ਜ਼ਿਰਾਕਸ ਐਂਡ ਕੰਪਨੀ ਦੁਆਰਾ ਲਾਇਸੰਸਸ਼ੁਦਾ \u00A9 2024",
            "made_with_love": "ਵਿਦਿਆਰਥੀਆਂ ਲਈ \u2764\uFE0F ਨਾਲ ਬਣਾਇਆ ਗਿਆ",
            "morning_express": "ਸਵੇਰ ਦੀ ਐਕਸਪ੍ਰੈਸ",
            "morning_desc": "ਸਵੇਰੇ 8 ਵਜੇ ਤੋਂ ਪਹਿਲਾਂ ਆਰਡਰ ਕਰੋ, 10:30 ਵਜੇ ਪ੍ਰਾਪਤ ਕਰੋ।",
            "live_pdf_desc": "ਤੁਰੰਤ ਸਫੇ ਸੰਪਾਦਿਤ ਕਰੋ, ਘੁੰਮਾਓ।",
            "glass_binding": "ਗਲਾਸ ਸ਼ੀਟ ਬਾਈਡਿੰਗ",
            "glass_desc": "ਪ੍ਰੀਮੀਅਮ ਬਾਈਡਿੰਗ ਹੁਣ ਉਪਲਬਧ ਹੈ।",
            "conditions_apply": "ਸ਼ਰਤਾਂ ਲਾਗੂ",
            "track_latest": "ਲਾਈਵ ਸਥਿਤੀ: ਨਵੀਨਤਮ ਆਰਡਰ",
            "quote_1": "ਤਕਨਾਲੋਜੀ ਸਭ ਤੋਂ ਵਧੀਆ ਹੁੰਦੀ ਹੈ ਜਦੋਂ ਇਹ ਲੋਕਾਂ ਨੂੰ ਇਕੱਠਾ ਕਰਦੀ ਹੈ।",
            "quote_author_1": "ਮੈਟ ਮੁਲੇਨਵੇਗ",
            "quote_2": "ਇਹ ਕੋਈ ਬੱਗ ਨਹੀਂ ਹੈ, ਇਹ ਇੱਕ ਵਿਸ਼ੇਸ਼ਤਾ ਹੈ।",
            "quote_author_2": "ਅਣਜਾਣ",
            "quote_3": "ਗੱਲਾਂ ਸਸਤੀਆਂ ਹਨ। ਮੈਨੂੰ ਕੋਡ ਦਿਖਾਓ।",
            "quote_author_3": "ਲੀਨਸ ਟੋਰਵਾਲਡਸ",
            "quote_4": "ਸਾਦਗੀ ਕੁਸ਼ਲਤਾ ਦੀ ਰੂਹ ਹੈ।",
            "quote_author_4": "ਆਸਟਿਨ ਫ੍ਰੀਮੈਨ",
            "quote_5": "ਭੁੱਖੇ ਰਹੋ, ਮੂਰਖ ਰਹੋ।",
            "quote_author_5": "ਸਟੀਵ ਜੌਬਸ"
        }
    },
    ur: {
        translation: {
            "welcome": "خوش آمدید",
            "login_title": "واپس خوش آمدید",
            "signup_title": "اکاؤنٹ بنائیں",
            "subtitle_login": "پرنٹنگ جاری رکھنے کے لیے سائن ان کریں",
            "subtitle_signup": "اسمارٹ پرنٹنگ کے لیے ہمارے ساتھ شامل ہوں۔",
            "mobile": "موبائل نمبر",
            "login": "لاگ ان",
            "signup": "سائن اپ",
            "brand_name": "اسمارٹ زیروکس",
            "nav_dashboard": "ڈیش بورڈ",
            "nav_login": "لاگ ان",
            "nav_signup": "سائن اپ",
            "nav_logout": "لاگ آؤٹ",
            "nav_profile": "پروفائل",
            "create_account": "اکاؤنٹ بنائیں",
            "welcome_back": "واپس خوش آمدید",
            "signup_subtitle": "سب سے ہوشیار پرنٹنگ نیٹ ورک میں شامل ہوں",
            "login_subtitle": "اپنا پریمیم تجربہ جاری رکھیں",
            "confirm_pass": "پاس ورڈ کی تصدیق کریں",
            "login_btn": "سائن ان",
            "already_account": "کیا آپ کے پاس پہلے سے اکاؤنٹ ہے؟",
            "no_account": "کیا اکاؤنٹ نہیں ہے؟",
            "dashboard": "ڈیش بورڈ",
            "logout": "لاگ آؤٹ",
            "overview": "جائزہ",
            "services": "خدمات",
            "support": "تعاون",
            "profile": "پروفائل",
            "total_orders": "کل آرڈرز",
            "total_spent": "کل خرچ",
            "saved": "محفوظ",
            "trusted_users": "قابل اعتماد صارفین",
            "recent_orders": "حالیہ آرڈرز",
            "our_services": "ہماری خدمات اور قیمتیں",
            "service_type": "سروس کی قسم",
            "single_side": "ایک طرف",
            "double_side": "دونوں اطراف",
            "bw_xerox": "زیروکس (بلیک اینڈ وائٹ)",
            "bw_print": "پرنٹ آؤٹ (بلیک اینڈ وائٹ)",
            "color_print": "کلر پرنٹ",
            "spiral": "سرپل بائنڈنگ",
            "glass_binding": "گلاس شیٹ بائنڈنگ",
            "launching_soon": "جلد آ رہا ہے",
            "no_orders": "کوئی آرڈر نہیں ملا۔ اپنا پہلا پرنٹ شروع کریں!",
            "create_first_order": "پہلا آرڈر بنائیں",
            "unbeatable_pricing": "ناقابل یقین قیمتیں",
            "secure_100": "100% محفوظ",
            "students_count": "1,200+ طلباء",
            "get_started": "ابھی شروع کریں",
            "add_items": "پرنٹ کرنے کے لیے آئٹمز شامل کریں",
            "your_list": "آپ کی آرڈر لسٹ",
            "pdf_module": "پی ڈی ایف ماڈیول",
            "doc_module": "دستاویزی ماڈیول",
            "upload_pdf_title": "پی ڈی ایف اپ لوڈ کریں",
            "browse_files": "اپنی فائلیں براؤز کرنے کے لیے کلک کریں",
            "preview": "پیش نظارہ",
            "edit_pages": "صفحات میں ترمیم کریں",
            "manual_format": "دستی فارمیٹنگ",
            "manual_format_desc": "ورڈ دستاویزات کو درست ترتیب کو یقینی بنانے کے لیے دستی پروسیسنگ کی ضرورت ہوتی ہے۔ براہ کرم واٹس ایپ کے ذریعے تصدیق کریں۔",
            "chat_whatsapp": "واٹس ایپ پر بات کریں",
            "special_instr": "خصوصی ہدایات",
            "instr_placeholder": "جیسے سرپل بائنڈنگ، لیمینیشن، صرف طاق صفحات پرنٹ کریں...",
            "advance_pay_label": "ادائیگی کے لیے ایڈوانس (50%)",
            "submit_pay": "جمع کرائیں اور ادائیگی کریں",
            "premium_services": "پریمیم خدمات",
            "word_docs": "ورڈ دستاویزات",
            "word_coming_soon": "اپ لوڈ، ترمیم اور کنورٹر کی خصوصیات",
            "live_pdf_editor": "لائیو پی ڈی ایف ایڈیٹر",
            "live_editor_desc": "بیرونی اوزار کی کوئی ضرورت نہیں. ناپسندیدہ صفحات کو ہٹا دیں، واقفیت کو گھمائیں، اور اپنی دستاویز کو یہاں ہمارے ٹیب میں حتمی شکل دیں۔",
            "digital_deliver": "ڈیجیٹل ڈیلیوری",
            "digital_desc": "اپنے فزیکل پرنٹس کے ساتھ ڈیجیٹل کاپیاں حاصل کریں۔ ہم آپ کی اہم دستاویزات کو آسانی سے دوبارہ آرڈر کرنے کے لیے محفوظ طریقے سے اسٹور کرتے ہیں۔",
            "quality_quote": "\"جہاں معیار رفتار سے ملتا ہے\"",
            "new_feature": "نئی خصوصیت",
            "contact_support": "رابطہ اور تعاون",
            "need_help_desc": "آرڈر کے ساتھ مدد چاہیے؟ دستی دستاویز کی فارمیٹنگ چاہتے ہیں؟ واٹس ایپ پر ہمارے ساتھ براہ راست چیٹ کریں۔",
            "support_hours": "تعاون کے اوقات",
            "trust_secure": "100% محفوظ",
            "trust_secure_desc": "انکرپٹڈ ادائیگیاں اور ڈیٹا کی رازداری",
            "trust_fast": "آسمانی بجلی کی تیزی",
            "trust_fast_desc": "24 گھنٹے ڈیلیوری کی ضمانت",
            "trust_quality": "بہترین معیار",
            "trust_quality_desc": "پریمیم کاغذ اور کرکرا پرنٹس",
            "spending_analysis": "اخراجات کا تجزیہ",
            "last_7_days": "گزشتہ 7 دن",
            "daily_quote": "روزانہ کی ترغیب",
            "design_quote": "ڈیزائن صرف وہ نہیں جو اسے لگتا ہے اور محسوس ہوتا ہے۔ ڈیزائن یہ ہے کہ یہ کیسے کام کرتا ہے۔",
            "lic_footer": "سمارٹ زیروکس اینڈ کمپنی کے ذریعہ لائسنس یافتہ \u00A9 2024",
            "made_with_love": "طلباء کے لیے \u2764\uFE0F کے ساتھ بنایا گیا",
            "morning_express": "مارننگ ایکسپریس",
            "morning_desc": "صبح 8 بجے سے پہلے آرڈر کریں، 10:30 بجے حاصل کریں۔",
            "live_pdf_desc": "فوری طور پر صفحات میں ترمیم کریں، گھمائیں۔",
            "glass_binding": "گلاس شیٹ بائنڈنگ",
            "glass_desc": "پریمیم بائنڈنگ اب دستیاب ہے۔",
            "conditions_apply": "شرائط لاگو",
            "track_latest": "لائیو اسٹیٹس: تازہ ترین آرڈر",
            "quote_1": "ٹیکنالوجی سب سے بہتر ہے جب یہ لوگوں کو اکٹھا کرتی ہے۔",
            "quote_author_1": "میٹ مولینویگ",
            "quote_2": "یہ کوئی بگ نہیں ہے، یہ ایک خصوصیت ہے۔",
            "quote_author_2": "نامعلوم",
            "quote_3": "باتیں سستی ہیں۔ مجھے کوڈ دکھائیں۔",
            "quote_author_3": "لینس ٹوروالڈس",
            "quote_4": "سادگی کارکردگی کی روح ہے۔",
            "quote_author_4": "آسٹن فری مین",
            "quote_5": "بھوکے رہو، بے وقوف رہو۔",
            "quote_author_5": "سٹیو جابز"
        }
    }
};
